// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package store

import (
	"context"
	"time"

	ulid "github.com/oklog/ulid/v2"
)

const countUnreadActivity = `-- name: CountUnreadActivity :one
WITH my_rooms AS (
    SELECT rm.room_id, r.kind AS room_kind, rm.last_read_user_seq,
           coalesce(rm.notify_level, wm.notify_level, 'mentions') AS effective_level
      FROM room_members rm
      JOIN rooms r ON r.id = rm.room_id
      JOIN workspace_members wm ON wm.workspace_id = r.workspace_id AND wm.user_id = rm.user_id
     WHERE rm.user_id = $1
       AND r.workspace_id = $3
       AND NOT (rm.muted AND (rm.muted_until IS NULL OR rm.muted_until > $4::timestamptz))
       AND CASE WHEN r.kind = 'dm' THEN coalesce(wm.notify_level, 'mentions') <> 'none'
                ELSE coalesce(rm.notify_level, wm.notify_level, 'mentions') <> 'none'
           END
),
candidates AS (
    SELECT mm.message_id
      FROM my_rooms mr
      JOIN message_mentions mm ON mm.room_id = mr.room_id
     WHERE mm.user_id IS NULL OR mm.user_id = $1
    UNION
    SELECT m.id
      FROM my_rooms mr
      JOIN messages m ON m.room_id = mr.room_id
     WHERE mr.room_kind = 'dm'
    UNION
    SELECT m.id
      FROM thread_members tm
      JOIN my_rooms mr ON mr.room_id = tm.room_id
      JOIN messages m ON m.thread_root_id = tm.thread_root_id
     WHERE tm.user_id = $1
       AND tm.notify_replies
    UNION
    SELECT m.id
      FROM my_rooms mr
      JOIN messages m ON m.room_id = mr.room_id AND m.in_channel
     WHERE mr.room_kind <> 'dm'
       AND mr.effective_level = 'all'
)
SELECT count(*)::bigint
  FROM (
    SELECT 1
      FROM candidates c
      JOIN messages m ON m.id = c.message_id
      JOIN my_rooms mr ON mr.room_id = m.room_id
      LEFT JOIN thread_members tm ON tm.thread_root_id = m.thread_root_id AND tm.user_id = $1
     WHERE m.kind = 'user'
       AND m.sender_id <> $1
       AND m.deleted_at IS NULL
       AND CASE WHEN m.in_channel THEN m.user_seq > mr.last_read_user_seq
                ELSE coalesce(m.thread_seq > tm.last_read_thread_seq, false)
           END
     LIMIT $2
  ) unread
`

type CountUnreadActivityParams struct {
	UserID      ulid.ULID
	MaxRows     int32
	WorkspaceID ulid.ULID
	Now         time.Time
}

// 未読のアクティビティの件数（メニューのバッジ）。max_rows で打ち切る（100 以上は「99+」。決定 5）。
// リアクションは未読を持たないので数えない。
func (q *Queries) CountUnreadActivity(ctx context.Context, arg CountUnreadActivityParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadActivity,
		arg.UserID,
		arg.MaxRows,
		arg.WorkspaceID,
		arg.Now,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getReaction = `-- name: GetReaction :one
SELECT created_at
  FROM message_reactions
 WHERE message_id = $1
   AND user_id = $2
   AND emoji = $3
`

type GetReactionParams struct {
	MessageID ulid.ULID
	UserID    ulid.ULID
	Emoji     string
}

// 付けたリアクションの 1 行（本人宛てのイベントの occurred_at に使う）。
func (q *Queries) GetReaction(ctx context.Context, arg GetReactionParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, getReaction, arg.MessageID, arg.UserID, arg.Emoji)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const listActivity = `-- name: ListActivity :many

WITH my_rooms AS (
    -- 自分がメンバーのルームだけを見る（決定 4）。外されたら room_members の行が消えるので、何もしなくても出なくなる。
    -- ミュート中と「なし」のルームは、ここで落とす（規則の最初の 2 行）。
    SELECT rm.room_id, r.kind AS room_kind, rm.last_read_user_seq,
           coalesce(rm.notify_level, wm.notify_level, 'mentions') AS effective_level
      FROM room_members rm
      JOIN rooms r ON r.id = rm.room_id
      JOIN workspace_members wm ON wm.workspace_id = r.workspace_id AND wm.user_id = rm.user_id
     WHERE rm.user_id = $6
       AND r.workspace_id = $7
       AND NOT (rm.muted AND (rm.muted_until IS NULL OR rm.muted_until > $8::timestamptz))
       -- DM は全体の設定が none でなければ対象。チャンネルは「通知する内容」（上書き、なければ全体）が none なら何も出さない
       AND CASE WHEN r.kind = 'dm' THEN coalesce(wm.notify_level, 'mentions') <> 'none'
                ELSE coalesce(rm.notify_level, wm.notify_level, 'mentions') <> 'none'
           END
),
candidates AS (
    -- 理由ごとの候補。1 つのメッセージが複数の理由に当たれば、ここでは複数行になる（items でまとめる）。
    -- メンション: 自分宛て（user_id = 自分。@here の解決結果も含む）か @channel（user_id が NULL）
    SELECT mm.message_id, 'mention'::text AS reason
      FROM my_rooms mr
      JOIN message_mentions mm ON mm.room_id = mr.room_id
     WHERE mm.user_id IS NULL OR mm.user_id = $6
    UNION ALL
    -- DM: すべて（スレッドの返信も。ADR 0057 決定 1 の表）
    SELECT m.id, 'dm'
      FROM my_rooms mr
      JOIN messages m ON m.room_id = mr.room_id
     WHERE mr.room_kind = 'dm'
    UNION ALL
    -- スレッド: 参加していて返信の通知がオンのスレッドの返信（ADR 0056 決定 3）
    SELECT m.id, 'thread'
      FROM thread_members tm
      JOIN my_rooms mr ON mr.room_id = tm.room_id
      JOIN messages m ON m.thread_root_id = tm.thread_root_id
     WHERE tm.user_id = $6
       AND tm.notify_replies
    UNION ALL
    -- 「すべての新しい投稿」: チャンネルに出た投稿だけ（スレッドだけの返信は、上の 2 つに当たるときだけ）
    SELECT m.id, 'channel'
      FROM my_rooms mr
      JOIN messages m ON m.room_id = mr.room_id AND m.in_channel
     WHERE mr.room_kind <> 'dm'
       AND mr.effective_level = 'all'
),
items AS (
    SELECT 'message'::text AS item_type, m.id AS message_id, m.room_id, NULL::uuid AS reactor_id, NULL::text AS emoji,
           m.created_at AS occurred_at, ('m:' || m.id::text)::text AS sort_key,
           array_agg(DISTINCT c.reason ORDER BY c.reason)::text[] AS reasons,
           -- 未読は未読数と同じ物差し（決定 5）。スレッドだけの返信は、参加していなければ未読にしない
           bool_or(CASE WHEN m.in_channel THEN m.user_seq > mr.last_read_user_seq
                        ELSE coalesce(m.thread_seq > tm.last_read_thread_seq, false)
                   END) AS unread
      FROM candidates c
      JOIN messages m ON m.id = c.message_id
      JOIN my_rooms mr ON mr.room_id = m.room_id
      LEFT JOIN thread_members tm ON tm.thread_root_id = m.thread_root_id AND tm.user_id = $6
     WHERE m.kind = 'user'
       AND m.sender_id <> $6
       AND m.deleted_at IS NULL
     GROUP BY m.id
    UNION ALL
    -- 自分のメッセージに、ほかの人が付けたリアクション。1 行が 1 件で、未読の状態は持たない（決定 5）
    SELECT 'reaction', m.id, m.room_id, re.user_id, re.emoji,
           re.created_at, 'r:' || m.id::text || ':' || re.user_id::text || ':' || re.emoji,
           ARRAY['reaction']::text[], false
      FROM my_rooms mr
      JOIN messages m ON m.room_id = mr.room_id AND m.sender_id = $6
      JOIN message_reactions re ON re.message_id = m.id
     WHERE re.user_id <> $6
       AND m.kind = 'user'
       AND m.deleted_at IS NULL
)
SELECT item_type, message_id, room_id, reactor_id, emoji, occurred_at, sort_key, reasons, unread
  FROM items
 WHERE ($1::text = 'all' OR $1::text = ANY(reasons))
   AND (NOT $2::boolean OR unread)
   AND (occurred_at, sort_key) < ($3::timestamptz, $4::text)
 ORDER BY occurred_at DESC, sort_key DESC
 LIMIT $5
`

type ListActivityParams struct {
	Filter      string
	UnreadOnly  bool
	BeforeAt    time.Time
	BeforeKey   string
	MaxRows     int32
	UserID      ulid.ULID
	WorkspaceID ulid.ULID
	Now         time.Time
}

type ListActivityRow struct {
	ItemType   string
	MessageID  ulid.ULID
	RoomID     ulid.ULID
	ReactorID  *ulid.ULID
	Emoji      *string
	OccurredAt time.Time
	SortKey    string
	Reasons    []string
	Unread     bool
}

// アクティビティ（ADR 0058）。
//
// 行を持たない。通知の規則（ADR 0055 決定 1・ADR 0056 決定 3・ADR 0057 決定 1）と、ルーム・スレッドの既読位置から
// 読むたびに組み立てる。@channel や「すべての新しい投稿」で人数分の行を書かないため（決定 5 の理由）。
//
// 規則は web/lib/chat/notifications/desktop-notification.ts の shouldNotify と同じ。違うのは次の 2 点だけ（決定 2）。
//   - 「どのタブも見えていない」を見ない（後から見る一覧なので）
//   - @here もメンションに数える（行があるのは送った瞬間にアクティブだった人だけ）
//
// 規則の表は testdata/notification-rules.json にあり、Go と Vitest の両方のテストが読む。片方だけ直さないこと。
//
// 3 つのクエリの CTE（my_rooms / candidates / items）は同じもの。sqlc はクエリをまたいで CTE を共有できないので、
// 3 か所に同じ形で書いてある。直すときは 3 か所とも直すこと。
// 一覧の 1 ページ。新しい順で、同じ時刻は sort_key で決める（決定 6）。
// 並びは created_at だが、ルームをまたいだ一覧の見せ方にしか使わない（同期の根拠は seq のまま。CLAUDE.md ルール 3 の範囲外）。
func (q *Queries) ListActivity(ctx context.Context, arg ListActivityParams) ([]ListActivityRow, error) {
	rows, err := q.db.Query(ctx, listActivity,
		arg.Filter,
		arg.UnreadOnly,
		arg.BeforeAt,
		arg.BeforeKey,
		arg.MaxRows,
		arg.UserID,
		arg.WorkspaceID,
		arg.Now,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityRow{}
	for rows.Next() {
		var i ListActivityRow
		if err := rows.Scan(
			&i.ItemType,
			&i.MessageID,
			&i.RoomID,
			&i.ReactorID,
			&i.Emoji,
			&i.OccurredAt,
			&i.SortKey,
			&i.Reasons,
			&i.Unread,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactionActivityTarget = `-- name: ReactionActivityTarget :one
SELECT EXISTS (
    SELECT 1
      FROM room_members rm
      JOIN rooms r ON r.id = rm.room_id
      JOIN workspace_members wm ON wm.workspace_id = r.workspace_id AND wm.user_id = rm.user_id
     WHERE rm.room_id = $1
       AND rm.user_id = $2
       AND NOT (rm.muted AND (rm.muted_until IS NULL OR rm.muted_until > $3::timestamptz))
       AND CASE WHEN r.kind = 'dm' THEN coalesce(wm.notify_level, 'mentions') <> 'none'
                ELSE coalesce(rm.notify_level, wm.notify_level, 'mentions') <> 'none'
           END
)::boolean
`

type ReactionActivityTargetParams struct {
	RoomID ulid.ULID
	UserID ulid.ULID
	Now    time.Time
}

// リアクションを付けた・外したとき、送信者のアクティビティに載るルームか（本人宛てのイベントを配るか。決定 9）。
// 一覧の my_rooms と同じ条件（メンバーで、ミュート中でも「なし」でもない）。
func (q *Queries) ReactionActivityTarget(ctx context.Context, arg ReactionActivityTargetParams) (bool, error) {
	row := q.db.QueryRow(ctx, reactionActivityTarget, arg.RoomID, arg.UserID, arg.Now)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
