// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package store

import (
	"context"
	"time"

	ulid "github.com/oklog/ulid/v2"
)

const attachToMessage = `-- name: AttachToMessage :many
UPDATE attachments
   SET status = 'attached',
       message_id = $1
 WHERE id = ANY($2::uuid[])
   AND room_id = $3
   AND uploader_id = $4
   AND status = 'uploaded'
RETURNING id
`

type AttachToMessageParams struct {
	MessageID  *ulid.ULID
	Ids        []ulid.ULID
	RoomID     ulid.ULID
	UploaderID ulid.ULID
}

// 送信のトランザクションで、メッセージの INSERT の後に呼ぶ。返った件数が ids の数と違えば、呼び出し側がロールバックする。
// 他人の添付、別のルームの添付、未検証の添付、使用済みの添付は、どれもこの条件で弾かれる。
// 同じ添付を並行した送信が使おうとしても、2 本目は行ロックを待ってから status の条件を満たさなくなる。
func (q *Queries) AttachToMessage(ctx context.Context, arg AttachToMessageParams) ([]ulid.ULID, error) {
	rows, err := q.db.Query(ctx, attachToMessage,
		arg.MessageID,
		arg.Ids,
		arg.RoomID,
		arg.UploaderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ulid.ULID{}
	for rows.Next() {
		var id ulid.ULID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAttachment = `-- name: CreateAttachment :exec

INSERT INTO attachments (id, room_id, uploader_id, status, object_key, file_name, mime_type, size_bytes, width, height, created_at)
VALUES ($1, $2, $3, 'pending', $4, $5,
        $6, $7, $8, $9, $10::timestamptz)
`

type CreateAttachmentParams struct {
	ID         ulid.ULID
	RoomID     ulid.ULID
	UploaderID ulid.ULID
	ObjectKey  string
	FileName   string
	MimeType   string
	SizeBytes  int64
	Width      *int32
	Height     *int32
	Now        time.Time
}

// 添付ファイル（ADR 0008 / 0013）。
//
// 状態は pending（URL を発行した）→ uploaded（HEAD で検証した）→ attached（メッセージに付いた）→ deleted（メッセージが削除された）。
// 状態を進める UPDATE は、どれも WHERE に「進める前の状態」を含める。並行した操作のうち 1 つだけが行を更新できる。
func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error {
	_, err := q.db.Exec(ctx, createAttachment,
		arg.ID,
		arg.RoomID,
		arg.UploaderID,
		arg.ObjectKey,
		arg.FileName,
		arg.MimeType,
		arg.SizeBytes,
		arg.Width,
		arg.Height,
		arg.Now,
	)
	return err
}

const deleteAttachments = `-- name: DeleteAttachments :exec
DELETE FROM attachments
 WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteAttachments(ctx context.Context, ids []ulid.ULID) error {
	_, err := q.db.Exec(ctx, deleteAttachments, ids)
	return err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, room_id, uploader_id, message_id, status, object_key, mime_type, size_bytes, width, height, created_at, file_name
  FROM attachments
 WHERE id = $1
`

func (q *Queries) GetAttachment(ctx context.Context, id ulid.ULID) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UploaderID,
		&i.MessageID,
		&i.Status,
		&i.ObjectKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.FileName,
	)
	return i, err
}

const listAttachmentsForMessages = `-- name: ListAttachmentsForMessages :many
SELECT id, message_id, file_name, mime_type, size_bytes, width, height
  FROM attachments
 WHERE room_id = $1
   AND message_id = ANY($2::uuid[])
   AND status = 'attached'
 ORDER BY message_id, id
`

type ListAttachmentsForMessagesParams struct {
	RoomID     ulid.ULID
	MessageIds []ulid.ULID
}

type ListAttachmentsForMessagesRow struct {
	ID        ulid.ULID
	MessageID *ulid.ULID
	FileName  string
	MimeType  string
	SizeBytes int64
	Width     *int32
	Height    *int32
}

// メッセージの一覧に添付を載せる。メッセージを読んだ後に 1 文でまとめて読む（N+1 にしない）。
// インデックス attachments_room_id_message_id_idx を使う。並びは発行順（id）。
func (q *Queries) ListAttachmentsForMessages(ctx context.Context, arg ListAttachmentsForMessagesParams) ([]ListAttachmentsForMessagesRow, error) {
	rows, err := q.db.Query(ctx, listAttachmentsForMessages, arg.RoomID, arg.MessageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttachmentsForMessagesRow{}
	for rows.Next() {
		var i ListAttachmentsForMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.FileName,
			&i.MimeType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAttachmentsForCleanup = `-- name: LockAttachmentsForCleanup :many
SELECT id, object_key
  FROM attachments
 WHERE status <> 'attached'
   AND (status = 'deleted' OR created_at < $1::timestamptz)
 ORDER BY created_at
 LIMIT $2
   FOR UPDATE SKIP LOCKED
`

type LockAttachmentsForCleanupParams struct {
	StaleBefore time.Time
	MaxRows     int32
}

type LockAttachmentsForCleanupRow struct {
	ID        ulid.ULID
	ObjectKey string
}

// 掃除ジョブの対象を行ロックして取る。SKIP LOCKED で、複数台が同時に実行しても同じ行を取り合わない。
// 「status <> 'attached'」は冗長に見えるが、部分インデックス attachments_cleanup_idx の条件と一致させて、インデックスを使わせるために書く。
func (q *Queries) LockAttachmentsForCleanup(ctx context.Context, arg LockAttachmentsForCleanupParams) ([]LockAttachmentsForCleanupRow, error) {
	rows, err := q.db.Query(ctx, lockAttachmentsForCleanup, arg.StaleBefore, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockAttachmentsForCleanupRow{}
	for rows.Next() {
		var i LockAttachmentsForCleanupRow
		if err := rows.Scan(&i.ID, &i.ObjectKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAttachmentUploaded = `-- name: MarkAttachmentUploaded :one
UPDATE attachments
   SET status = 'uploaded'
 WHERE id = $1
   AND status = 'pending'
RETURNING id, room_id, uploader_id, message_id, status, object_key, mime_type, size_bytes, width, height, created_at, file_name
`

// complete の HEAD はトランザクションの外で行い、その後にこの 1 文で状態を進める。
// 並行した complete や掃除ジョブに先を越されていれば行を返さないので、呼び出し側が読み直す。
func (q *Queries) MarkAttachmentUploaded(ctx context.Context, id ulid.ULID) (Attachment, error) {
	row := q.db.QueryRow(ctx, markAttachmentUploaded, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UploaderID,
		&i.MessageID,
		&i.Status,
		&i.ObjectKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.FileName,
	)
	return i, err
}

const markMessageAttachmentsDeleted = `-- name: MarkMessageAttachmentsDeleted :exec
UPDATE attachments
   SET status = 'deleted'
 WHERE room_id = $1
   AND message_id = $2
   AND status = 'attached'
`

type MarkMessageAttachmentsDeletedParams struct {
	RoomID    ulid.ULID
	MessageID *ulid.ULID
}

// メッセージの論理削除と同じトランザクションで呼ぶ。ストレージのオブジェクトは掃除ジョブが消す。
func (q *Queries) MarkMessageAttachmentsDeleted(ctx context.Context, arg MarkMessageAttachmentsDeletedParams) error {
	_, err := q.db.Exec(ctx, markMessageAttachmentsDeleted, arg.RoomID, arg.MessageID)
	return err
}
