// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: huddles.sql

package store

import (
	"context"
	"time"

	ulid "github.com/oklog/ulid/v2"
)

const addHuddleParticipant = `-- name: AddHuddleParticipant :execrows
INSERT INTO huddle_participants (huddle_id, user_id, joined_at)
VALUES ($1, $2, $3::timestamptz)
ON CONFLICT (huddle_id, user_id) DO NOTHING
`

type AddHuddleParticipantParams struct {
	HuddleID ulid.ULID
	UserID   ulid.ULID
	Now      time.Time
}

// 一度でも入った人を 1 回だけ書く（決定 3）。返す行数が 1 なら初めて入った（会話のメッセージの参加者が増えた）。
func (q *Queries) AddHuddleParticipant(ctx context.Context, arg AddHuddleParticipantParams) (int64, error) {
	result, err := q.db.Exec(ctx, addHuddleParticipant, arg.HuddleID, arg.UserID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const allocateHuddleChangeSeq = `-- name: AllocateHuddleChangeSeq :one
UPDATE rooms
   SET last_change_seq = last_change_seq + 1
 WHERE id = $1
RETURNING last_change_seq
`

// ハドルのメッセージの change_seq を 1 つ採番する（参加した人が増えた・終わった。決定 12）。
// AllocateChangeSeq と違い、アーカイブ中でも採番する。アーカイブするときに進行中のハドルを終わらせ（決定 7）、
// 終わったことを差分の同期でもそろえるため（アーカイブのログと同じ考え方。ADR 0059）。
func (q *Queries) AllocateHuddleChangeSeq(ctx context.Context, roomID ulid.ULID) (int64, error) {
	row := q.db.QueryRow(ctx, allocateHuddleChangeSeq, roomID)
	var last_change_seq int64
	err := row.Scan(&last_change_seq)
	return last_change_seq, err
}

const createHuddle = `-- name: CreateHuddle :exec
INSERT INTO huddles (id, room_id, started_by, message_id, started_at)
VALUES ($1, $2, $3, $4, $5::timestamptz)
`

type CreateHuddleParams struct {
	ID        ulid.ULID
	RoomID    ulid.ULID
	StartedBy ulid.ULID
	MessageID ulid.ULID
	Now       time.Time
}

// 進行中のハドルは部分 UNIQUE インデックス（huddles_room_id_active_idx）で 1 ルームに 1 つに限る。
// 2 人が同時に始めたら後の方が一意制約の違反になり、呼び出し側は先のハドルに入り直す。
func (q *Queries) CreateHuddle(ctx context.Context, arg CreateHuddleParams) error {
	_, err := q.db.Exec(ctx, createHuddle,
		arg.ID,
		arg.RoomID,
		arg.StartedBy,
		arg.MessageID,
		arg.Now,
	)
	return err
}

const endHuddle = `-- name: EndHuddle :exec
UPDATE huddles
   SET ended_at = $1::timestamptz
 WHERE id = $2
   AND ended_at IS NULL
`

type EndHuddleParams struct {
	Now time.Time
	ID  ulid.ULID
}

func (q *Queries) EndHuddle(ctx context.Context, arg EndHuddleParams) error {
	_, err := q.db.Exec(ctx, endHuddle, arg.Now, arg.ID)
	return err
}

const getHuddle = `-- name: GetHuddle :one
SELECT id, room_id, started_by, message_id, started_at, ended_at
  FROM huddles
 WHERE id = $1
`

func (q *Queries) GetHuddle(ctx context.Context, id ulid.ULID) (Huddle, error) {
	row := q.db.QueryRow(ctx, getHuddle, id)
	var i Huddle
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.StartedBy,
		&i.MessageID,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getHuddleRoom = `-- name: GetHuddleRoom :one
SELECT h.id, h.room_id, h.ended_at, r.workspace_id, r.kind
  FROM huddles h
  JOIN rooms r ON r.id = h.room_id
 WHERE h.id = $1
`

type GetHuddleRoomRow struct {
	ID          ulid.ULID
	RoomID      ulid.ULID
	EndedAt     *time.Time
	WorkspaceID ulid.ULID
	Kind        string
}

// ハドルのルームとワークスペース（権限が変わった人をハドルから外すとき、そのハドルが対象かを決める。決定 8）。
func (q *Queries) GetHuddleRoom(ctx context.Context, id ulid.ULID) (GetHuddleRoomRow, error) {
	row := q.db.QueryRow(ctx, getHuddleRoom, id)
	var i GetHuddleRoomRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.EndedAt,
		&i.WorkspaceID,
		&i.Kind,
	)
	return i, err
}

const listActiveHuddlesInRooms = `-- name: ListActiveHuddlesInRooms :many
SELECT id, room_id, message_id, started_at
  FROM huddles
 WHERE room_id = ANY($1::uuid[])
   AND ended_at IS NULL
`

type ListActiveHuddlesInRoomsRow struct {
	ID        ulid.ULID
	RoomID    ulid.ULID
	MessageID ulid.ULID
	StartedAt time.Time
}

// ルームの一覧と 1 件の取得に、進行中のハドルを添える（決定 13）。いま入っている人は Redis から読む。
func (q *Queries) ListActiveHuddlesInRooms(ctx context.Context, roomIds []ulid.ULID) ([]ListActiveHuddlesInRoomsRow, error) {
	rows, err := q.db.Query(ctx, listActiveHuddlesInRooms, roomIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveHuddlesInRoomsRow{}
	for rows.Next() {
		var i ListActiveHuddlesInRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.MessageID,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHuddleSuggestions = `-- name: ListHuddleSuggestions :many
SELECT h.room_id, r.kind AS room_kind, r.name AS room_name, r.dm_key AS room_dm_key, r.is_default AS room_is_default,
       count(*)::bigint AS huddle_count,
       max(h.started_at)::timestamptz AS last_started_at,
       COALESCE((SELECT array_agg(DISTINCT p2.user_id)
                   FROM huddles h2
                   JOIN huddle_participants p2 ON p2.huddle_id = h2.id
                  WHERE h2.room_id = h.room_id
                    AND h2.started_at >= $1::timestamptz
                    AND p2.user_id <> $2), '{}')::uuid[] AS participant_ids
  FROM huddle_participants me
  JOIN huddles h ON h.id = me.huddle_id
  JOIN rooms r ON r.id = h.room_id
  JOIN room_members rm ON rm.room_id = r.id AND rm.user_id = me.user_id
 WHERE me.user_id = $2
   AND r.workspace_id = $3
   AND r.archived_at IS NULL
   AND h.started_at >= $1::timestamptz
   AND NOT EXISTS (SELECT 1 FROM huddles a WHERE a.room_id = h.room_id AND a.ended_at IS NULL)
 GROUP BY h.room_id, r.kind, r.name, r.dm_key, r.is_default
 ORDER BY huddle_count DESC, last_started_at DESC
 LIMIT $4
`

type ListHuddleSuggestionsParams struct {
	Since       time.Time
	UserID      ulid.ULID
	WorkspaceID ulid.ULID
	MaxRows     int32
}

type ListHuddleSuggestionsRow struct {
	RoomID         ulid.ULID
	RoomKind       string
	RoomName       *string
	RoomDmKey      *string
	RoomIsDefault  bool
	HuddleCount    int64
	LastStartedAt  time.Time
	ParticipantIds []ulid.ULID
}

// 提案のカード（ADR 0067 決定 7）。since 以降に自分が参加したハドルがあったルームを、回数の多い順に返す（同じなら新しい方）。
// 候補は自分がいまメンバーで、アーカイブしていないルームだけ（入れるかの最後の判断はサービスが authz で行う）。
// いまハドルが進行中のルームは除く（一覧の上の進行中のカードに出る）。
// 顔に出す人は、そのルームの同じ期間のハドルに参加した人（自分を除く）。
func (q *Queries) ListHuddleSuggestions(ctx context.Context, arg ListHuddleSuggestionsParams) ([]ListHuddleSuggestionsRow, error) {
	rows, err := q.db.Query(ctx, listHuddleSuggestions,
		arg.Since,
		arg.UserID,
		arg.WorkspaceID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHuddleSuggestionsRow{}
	for rows.Next() {
		var i ListHuddleSuggestionsRow
		if err := rows.Scan(
			&i.RoomID,
			&i.RoomKind,
			&i.RoomName,
			&i.RoomDmKey,
			&i.RoomIsDefault,
			&i.HuddleCount,
			&i.LastStartedAt,
			&i.ParticipantIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHuddles = `-- name: ListHuddles :many
WITH readable_rooms AS (
    SELECT r.id, r.kind, r.name, r.dm_key, rm.joined_at AS member_since
      FROM rooms r
      LEFT JOIN room_members rm ON rm.room_id = r.id AND rm.user_id = $1
     WHERE r.workspace_id = $7
       AND (r.kind = 'public' OR rm.user_id IS NOT NULL)
)
SELECT h.id, h.room_id, h.message_id, h.started_by, h.started_at, h.ended_at,
       rr.kind AS room_kind, rr.name AS room_name, rr.dm_key AS room_dm_key,
       m.thread_reply_count,
       COALESCE((SELECT array_agg(p.user_id ORDER BY p.joined_at, p.user_id)
                   FROM huddle_participants p
                  WHERE p.huddle_id = h.id), '{}')::uuid[] AS participant_ids,
       -- 自分がハドルのメッセージを「後で」に保存しているか（行の「…」の文言。外したものは removed で残る。ADR 0054）
       EXISTS (SELECT 1 FROM saved_messages s
                WHERE s.user_id = $1 AND s.message_id = h.message_id AND s.state <> 'removed') AS saved
  FROM huddles h
  JOIN readable_rooms rr ON rr.id = h.room_id
  JOIN messages m ON m.room_id = h.room_id AND m.id = h.message_id
 WHERE h.ended_at IS NOT NULL
   AND h.id < $2::uuid
   AND ($3::uuid IS NULL OR h.room_id = $3::uuid)
   AND ($4::uuid IS NULL OR EXISTS (
         SELECT 1 FROM huddle_participants p WHERE p.huddle_id = h.id AND p.user_id = $4::uuid))
   AND CASE
         WHEN $5::boolean THEN
           rr.member_since IS NOT NULL AND h.started_at >= rr.member_since
           AND NOT EXISTS (SELECT 1 FROM huddle_participants me WHERE me.huddle_id = h.id AND me.user_id = $1)
         ELSE
           (rr.member_since IS NOT NULL AND h.started_at >= rr.member_since)
           OR EXISTS (SELECT 1 FROM huddle_participants me WHERE me.huddle_id = h.id AND me.user_id = $1)
       END
 ORDER BY h.id DESC
 LIMIT $6
`

type ListHuddlesParams struct {
	UserID        ulid.ULID
	BeforeID      ulid.ULID
	RoomID        *ulid.ULID
	ParticipantID *ulid.ULID
	Missed        bool
	MaxRows       int32
	WorkspaceID   ulid.ULID
}

type ListHuddlesRow struct {
	ID               ulid.ULID
	RoomID           ulid.ULID
	MessageID        ulid.ULID
	StartedBy        ulid.ULID
	StartedAt        time.Time
	EndedAt          *time.Time
	RoomKind         string
	RoomName         *string
	RoomDmKey        *string
	ThreadReplyCount int32
	ParticipantIds   []ulid.ULID
	Saved            bool
}

// ハドルの一覧の「最近のハドルミーティング」（ADR 0067 決定 6）。終わったハドルを新しい順に 1 ページ返す。
//
// 出すのは、いま読める（`readable_rooms`）ルームのハドルのうち、
//   - missed = false（すべて）: 自分がいまメンバーのルームで、参加した後に始まったもの、または自分が入ったもの
//   - missed = true（参加しなかった）: 自分がいまメンバーのルームで、参加した後に始まったもので、自分が入っていないもの
//
// 参加する前のハドルを「参加しなかった」に入れないため、メンバーのルームのハドルは room_members.joined_at 以降に絞る。
// 参加していない public のチャンネルのハドルは、自分が入ったものだけ（アクティビティと同じ線引き。ADR 0058 決定 4）。
//
// `readable_rooms` は検索（search.sql）と同じ述語。**`authz.CanReadRoom` を変えたらここも直すこと**
// （`huddle_list_test.go` が同じ組み合わせを検査する）。アーカイブしたルームは外さない（読めるため。ADR 0059）。
//
// 参加した人と返信の数は同じ 1 文で読む（N+1 にしない）。参加した人は 20 人までなので全員を載せる。
// 並びはハドルの ID（始めたときの ULID）の降順。メッセージではないので、created_at で並べないルール 3 には当たらない。
func (q *Queries) ListHuddles(ctx context.Context, arg ListHuddlesParams) ([]ListHuddlesRow, error) {
	rows, err := q.db.Query(ctx, listHuddles,
		arg.UserID,
		arg.BeforeID,
		arg.RoomID,
		arg.ParticipantID,
		arg.Missed,
		arg.MaxRows,
		arg.WorkspaceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHuddlesRow{}
	for rows.Next() {
		var i ListHuddlesRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.MessageID,
			&i.StartedBy,
			&i.StartedAt,
			&i.EndedAt,
			&i.RoomKind,
			&i.RoomName,
			&i.RoomDmKey,
			&i.ThreadReplyCount,
			&i.ParticipantIds,
			&i.Saved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHuddlesOfMessages = `-- name: ListHuddlesOfMessages :many
SELECT h.id, h.message_id, h.started_at, h.ended_at,
       COALESCE(array_agg(p.user_id ORDER BY p.joined_at, p.user_id) FILTER (WHERE p.user_id IS NOT NULL), '{}')::uuid[] AS participant_ids
  FROM huddles h
  LEFT JOIN huddle_participants p ON p.huddle_id = h.id
 WHERE h.message_id = ANY($1::uuid[])
 GROUP BY h.id
`

type ListHuddlesOfMessagesRow struct {
	ID             ulid.ULID
	MessageID      ulid.ULID
	StartedAt      time.Time
	EndedAt        *time.Time
	ParticipantIds []ulid.ULID
}

// メッセージの応答の huddle（決定 12）。ページのハドルのメッセージをまとめて引く（N+1 にしない）。
// 参加した人は最初に入った順。20 人までなので全員を載せる。
func (q *Queries) ListHuddlesOfMessages(ctx context.Context, messageIds []ulid.ULID) ([]ListHuddlesOfMessagesRow, error) {
	rows, err := q.db.Query(ctx, listHuddlesOfMessages, messageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHuddlesOfMessagesRow{}
	for rows.Next() {
		var i ListHuddlesOfMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.StartedAt,
			&i.EndedAt,
			&i.ParticipantIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveHuddle = `-- name: LockActiveHuddle :one

SELECT id, room_id, started_by, message_id, started_at, ended_at
  FROM huddles
 WHERE room_id = $1
   AND ended_at IS NULL
   FOR UPDATE
`

// 音声のハドル（ADR 0066）。Postgres に置くのは履歴だけで、いま入っている人は Redis にある（決定 3）。
// ルームの進行中のハドルを行ロックして取る（決定 4）。
// 「入る」と「最後の人が抜けて終わる」はどちらもこの行をロックしてから Redis を見るので、終わったハドルに入ってしまうことがない。
func (q *Queries) LockActiveHuddle(ctx context.Context, roomID ulid.ULID) (Huddle, error) {
	row := q.db.QueryRow(ctx, lockActiveHuddle, roomID)
	var i Huddle
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.StartedBy,
		&i.MessageID,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const lockHuddle = `-- name: LockHuddle :one
SELECT id, room_id, started_by, message_id, started_at, ended_at
  FROM huddles
 WHERE id = $1
   FOR UPDATE
`

// ハドルを ID で行ロックして取る（終わらせる前に、まだ誰もいないかを確かめるため）。
func (q *Queries) LockHuddle(ctx context.Context, id ulid.ULID) (Huddle, error) {
	row := q.db.QueryRow(ctx, lockHuddle, id)
	var i Huddle
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.StartedBy,
		&i.MessageID,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}
