// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package store

import (
	"context"
	"time"

	ulid "github.com/oklog/ulid/v2"
)

const addWorkspaceMemberIfAbsent = `-- name: AddWorkspaceMemberIfAbsent :execrows
INSERT INTO workspace_members (workspace_id, user_id, role, joined_at)
VALUES ($1, $2, 'member', $3::timestamptz)
ON CONFLICT DO NOTHING
`

type AddWorkspaceMemberIfAbsentParams struct {
	WorkspaceID ulid.ULID
	UserID      ulid.ULID
	Now         time.Time
}

// 招待の受け入れでメンバーにする。すでにメンバーなら何もせず 0 を返す（使用回数を消費しない）。
// 同じユーザーの並行した受け入れは、主キーの一意性の確定を待ってから ON CONFLICT になる。
func (q *Queries) AddWorkspaceMemberIfAbsent(ctx context.Context, arg AddWorkspaceMemberIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, addWorkspaceMemberIfAbsent, arg.WorkspaceID, arg.UserID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeInvite = `-- name: ConsumeInvite :execrows
UPDATE workspace_invites
   SET use_count = use_count + 1
 WHERE id = $1
   AND revoked_at IS NULL
   AND expires_at > $2::timestamptz
   AND (max_uses IS NULL OR use_count < max_uses)
`

type ConsumeInviteParams struct {
	ID  ulid.ULID
	Now time.Time
}

// 有効な招待の使用回数を 1 増やす。条件を満たさなければ 0 行。
// 「読んで確かめてから加算」を 1 文にするので、並行した受け入れでも max_uses を超えない。
// 行ロックを待った後、Postgres は更新後の行で WHERE を評価し直す（READ COMMITTED）ので、
// 先に上限に達したトランザクションがコミットしたら、待っていた側は 0 行になる。
func (q *Queries) ConsumeInvite(ctx context.Context, arg ConsumeInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeInvite, arg.ID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createInvite = `-- name: CreateInvite :one

INSERT INTO workspace_invites (id, workspace_id, code_hash, created_by, max_uses, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5,
        $6, $7::timestamptz)
RETURNING id, workspace_id, code_hash, created_by, max_uses, use_count, expires_at, revoked_at, created_at
`

type CreateInviteParams struct {
	ID          ulid.ULID
	WorkspaceID ulid.ULID
	CodeHash    []byte
	CreatedBy   ulid.ULID
	MaxUses     *int32
	ExpiresAt   time.Time
	Now         time.Time
}

// 招待リンク（ADR 0006 / 0011）。コードは SHA-256 のハッシュだけを扱い、生の値は SQL に渡さない。
func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (WorkspaceInvite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.ID,
		arg.WorkspaceID,
		arg.CodeHash,
		arg.CreatedBy,
		arg.MaxUses,
		arg.ExpiresAt,
		arg.Now,
	)
	var i WorkspaceInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CodeHash,
		&i.CreatedBy,
		&i.MaxUses,
		&i.UseCount,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvite = `-- name: GetInvite :one
SELECT id, workspace_id, code_hash, created_by, max_uses, use_count, expires_at, revoked_at, created_at
  FROM workspace_invites
 WHERE id = $1
`

func (q *Queries) GetInvite(ctx context.Context, id ulid.ULID) (WorkspaceInvite, error) {
	row := q.db.QueryRow(ctx, getInvite, id)
	var i WorkspaceInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CodeHash,
		&i.CreatedBy,
		&i.MaxUses,
		&i.UseCount,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByCodeHash = `-- name: GetInviteByCodeHash :one
SELECT i.id, i.workspace_id, i.code_hash, i.created_by, i.max_uses, i.use_count, i.expires_at, i.revoked_at, i.created_at
  FROM workspace_invites i
  JOIN workspaces w ON w.id = i.workspace_id
 WHERE i.code_hash = $1
   AND w.deleted_at IS NULL
`

func (q *Queries) GetInviteByCodeHash(ctx context.Context, codeHash []byte) (WorkspaceInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByCodeHash, codeHash)
	var i WorkspaceInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CodeHash,
		&i.CreatedBy,
		&i.MaxUses,
		&i.UseCount,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitePreview = `-- name: GetInvitePreview :one
SELECT i.id, i.workspace_id, i.code_hash, i.created_by, i.max_uses, i.use_count, i.expires_at, i.revoked_at, i.created_at,
       w.name AS workspace_name,
       u.handle AS creator_handle,
       u.display_name AS creator_display_name,
       (SELECT count(*) FROM workspace_members m WHERE m.workspace_id = i.workspace_id) AS member_count,
       (SELECT count(*) FROM rooms r WHERE r.workspace_id = i.workspace_id AND r.kind = 'public') AS public_room_count,
       EXISTS (SELECT 1 FROM workspace_members m
                WHERE m.workspace_id = i.workspace_id AND m.user_id = $1) AS already_member
  FROM workspace_invites i
  JOIN workspaces w ON w.id = i.workspace_id
  JOIN users u ON u.id = i.created_by
 WHERE i.code_hash = $2
   AND w.deleted_at IS NULL
`

type GetInvitePreviewParams struct {
	UserID   ulid.ULID
	CodeHash []byte
}

type GetInvitePreviewRow struct {
	WorkspaceInvite    WorkspaceInvite
	WorkspaceName      string
	CreatorHandle      string
	CreatorDisplayName string
	MemberCount        int64
	PublicRoomCount    int64
	AlreadyMember      bool
}

// 招待のプレビュー。削除済みのワークスペースの招待は見つからないものとして扱う。
// 件数は招待を持っている人（まだメンバーではない人）に見せる値なので、public ルームだけを数える（private の存在は明かさない）。
func (q *Queries) GetInvitePreview(ctx context.Context, arg GetInvitePreviewParams) (GetInvitePreviewRow, error) {
	row := q.db.QueryRow(ctx, getInvitePreview, arg.UserID, arg.CodeHash)
	var i GetInvitePreviewRow
	err := row.Scan(
		&i.WorkspaceInvite.ID,
		&i.WorkspaceInvite.WorkspaceID,
		&i.WorkspaceInvite.CodeHash,
		&i.WorkspaceInvite.CreatedBy,
		&i.WorkspaceInvite.MaxUses,
		&i.WorkspaceInvite.UseCount,
		&i.WorkspaceInvite.ExpiresAt,
		&i.WorkspaceInvite.RevokedAt,
		&i.WorkspaceInvite.CreatedAt,
		&i.WorkspaceName,
		&i.CreatorHandle,
		&i.CreatorDisplayName,
		&i.MemberCount,
		&i.PublicRoomCount,
		&i.AlreadyMember,
	)
	return i, err
}

const getInviteWithCreator = `-- name: GetInviteWithCreator :one
SELECT i.id, i.workspace_id, i.code_hash, i.created_by, i.max_uses, i.use_count, i.expires_at, i.revoked_at, i.created_at, u.handle AS creator_handle, u.display_name AS creator_display_name
  FROM workspace_invites i
  JOIN users u ON u.id = i.created_by
 WHERE i.id = $1
   AND i.workspace_id = $2
`

type GetInviteWithCreatorParams struct {
	ID          ulid.ULID
	WorkspaceID ulid.ULID
}

type GetInviteWithCreatorRow struct {
	WorkspaceInvite    WorkspaceInvite
	CreatorHandle      string
	CreatorDisplayName string
}

func (q *Queries) GetInviteWithCreator(ctx context.Context, arg GetInviteWithCreatorParams) (GetInviteWithCreatorRow, error) {
	row := q.db.QueryRow(ctx, getInviteWithCreator, arg.ID, arg.WorkspaceID)
	var i GetInviteWithCreatorRow
	err := row.Scan(
		&i.WorkspaceInvite.ID,
		&i.WorkspaceInvite.WorkspaceID,
		&i.WorkspaceInvite.CodeHash,
		&i.WorkspaceInvite.CreatedBy,
		&i.WorkspaceInvite.MaxUses,
		&i.WorkspaceInvite.UseCount,
		&i.WorkspaceInvite.ExpiresAt,
		&i.WorkspaceInvite.RevokedAt,
		&i.WorkspaceInvite.CreatedAt,
		&i.CreatorHandle,
		&i.CreatorDisplayName,
	)
	return i, err
}

const joinDefaultRooms = `-- name: JoinDefaultRooms :many
INSERT INTO room_members (room_id, user_id, last_read_seq, last_read_user_seq, joined_at)
SELECT r.id, $1, r.last_message_seq, r.last_user_seq, $2::timestamptz
  FROM rooms r
 WHERE r.workspace_id = $3
   AND r.is_default
ON CONFLICT DO NOTHING
RETURNING room_id
`

type JoinDefaultRoomsParams struct {
	UserID      ulid.ULID
	Now         time.Time
	WorkspaceID ulid.ULID
}

// is_default のルームに参加する。last_read_seq は参加時点の最新の seq にする（参加前のメッセージを未読にしない）。
// 参加したルームを返す。本人と各ルームの購読者に member.joined を配信するため（ADR 0015）。
func (q *Queries) JoinDefaultRooms(ctx context.Context, arg JoinDefaultRoomsParams) ([]ulid.ULID, error) {
	rows, err := q.db.Query(ctx, joinDefaultRooms, arg.UserID, arg.Now, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ulid.ULID{}
	for rows.Next() {
		var room_id ulid.ULID
		if err := rows.Scan(&room_id); err != nil {
			return nil, err
		}
		items = append(items, room_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvites = `-- name: ListInvites :many
SELECT i.id, i.workspace_id, i.code_hash, i.created_by, i.max_uses, i.use_count, i.expires_at, i.revoked_at, i.created_at, u.handle AS creator_handle, u.display_name AS creator_display_name
  FROM workspace_invites i
  JOIN users u ON u.id = i.created_by
 WHERE i.workspace_id = $1
   AND ($2::uuid IS NULL OR i.id < $2::uuid)
 ORDER BY i.id DESC
 LIMIT $3
`

type ListInvitesParams struct {
	WorkspaceID ulid.ULID
	Before      *ulid.ULID
	MaxRows     int32
}

type ListInvitesRow struct {
	WorkspaceInvite    WorkspaceInvite
	CreatorHandle      string
	CreatorDisplayName string
}

// 新しい順。カーソルは直前のページの最後の id で、それより古いものを返す（NULL なら先頭から）。
func (q *Queries) ListInvites(ctx context.Context, arg ListInvitesParams) ([]ListInvitesRow, error) {
	rows, err := q.db.Query(ctx, listInvites, arg.WorkspaceID, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitesRow{}
	for rows.Next() {
		var i ListInvitesRow
		if err := rows.Scan(
			&i.WorkspaceInvite.ID,
			&i.WorkspaceInvite.WorkspaceID,
			&i.WorkspaceInvite.CodeHash,
			&i.WorkspaceInvite.CreatedBy,
			&i.WorkspaceInvite.MaxUses,
			&i.WorkspaceInvite.UseCount,
			&i.WorkspaceInvite.ExpiresAt,
			&i.WorkspaceInvite.RevokedAt,
			&i.WorkspaceInvite.CreatedAt,
			&i.CreatorHandle,
			&i.CreatorDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvite = `-- name: RevokeInvite :exec
UPDATE workspace_invites
   SET revoked_at = coalesce(revoked_at, $1::timestamptz)
 WHERE id = $2
   AND workspace_id = $3
`

type RevokeInviteParams struct {
	Now         time.Time
	ID          ulid.ULID
	WorkspaceID ulid.ULID
}

// すでに取り消し済みなら最初に取り消した日時を残す。
func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) error {
	_, err := q.db.Exec(ctx, revokeInvite, arg.Now, arg.ID, arg.WorkspaceID)
	return err
}
