// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: link_previews.sql

package store

import (
	"context"
	"time"

	ulid "github.com/oklog/ulid/v2"
)

const claimPendingMessageLinkPreview = `-- name: ClaimPendingMessageLinkPreview :one
UPDATE message_link_previews
   SET claimed_until = $1::timestamptz,
       attempts = attempts + 1
 WHERE id = (
        SELECT id
          FROM message_link_previews
         WHERE status = 'pending'
           AND removed_at IS NULL
           AND (claimed_until IS NULL OR claimed_until <= $2::timestamptz)
           AND ($3::uuid IS NULL OR room_id = $3::uuid)
         ORDER BY created_at
         LIMIT 1
           FOR UPDATE SKIP LOCKED
       )
RETURNING id, room_id, message_id, url, attempts
`

type ClaimPendingMessageLinkPreviewParams struct {
	ClaimedUntil time.Time
	Now          time.Time
	RoomID       *ulid.ULID
}

type ClaimPendingMessageLinkPreviewRow struct {
	ID        ulid.ULID
	RoomID    ulid.ULID
	MessageID ulid.ULID
	Url       string
	Attempts  int32
}

// 取得待ちを 1 件取り、claimed_until を立てる（決定 10）。取ってから commit し、ネットワークを待つ間はトランザクションを持たない。
// SKIP LOCKED で、複数台で動かしても同じ行を取り合わない。claimed_until が過ぎた行（ジョブが落ちた）も拾い直す。
// room_id はテストだけが渡す（テスト用 DB を共有するほかのテストの行を取らないため）。本番のジョブは null。
func (q *Queries) ClaimPendingMessageLinkPreview(ctx context.Context, arg ClaimPendingMessageLinkPreviewParams) (ClaimPendingMessageLinkPreviewRow, error) {
	row := q.db.QueryRow(ctx, claimPendingMessageLinkPreview, arg.ClaimedUntil, arg.Now, arg.RoomID)
	var i ClaimPendingMessageLinkPreviewRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.MessageID,
		&i.Url,
		&i.Attempts,
	)
	return i, err
}

const completeMessageLinkPreview = `-- name: CompleteMessageLinkPreview :exec
UPDATE message_link_previews
   SET status = $1,
       link_preview_id = $2,
       claimed_until = NULL
 WHERE id = $3
`

type CompleteMessageLinkPreviewParams struct {
	Status        string
	LinkPreviewID *ulid.ULID
	ID            ulid.ULID
}

func (q *Queries) CompleteMessageLinkPreview(ctx context.Context, arg CompleteMessageLinkPreviewParams) error {
	_, err := q.db.Exec(ctx, completeMessageLinkPreview, arg.Status, arg.LinkPreviewID, arg.ID)
	return err
}

const createLinkPreview = `-- name: CreateLinkPreview :exec
INSERT INTO link_previews (
    id, url, status, title, description, site_name,
    image_object_key, image_content_type, image_width, image_height,
    icon_object_key, icon_content_type, fetched_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13
)
`

type CreateLinkPreviewParams struct {
	ID               ulid.ULID
	Url              string
	Status           string
	Title            string
	Description      string
	SiteName         string
	ImageObjectKey   *string
	ImageContentType *string
	ImageWidth       *int32
	ImageHeight      *int32
	IconObjectKey    *string
	IconContentType  *string
	FetchedAt        time.Time
}

func (q *Queries) CreateLinkPreview(ctx context.Context, arg CreateLinkPreviewParams) error {
	_, err := q.db.Exec(ctx, createLinkPreview,
		arg.ID,
		arg.Url,
		arg.Status,
		arg.Title,
		arg.Description,
		arg.SiteName,
		arg.ImageObjectKey,
		arg.ImageContentType,
		arg.ImageWidth,
		arg.ImageHeight,
		arg.IconObjectKey,
		arg.IconContentType,
		arg.FetchedAt,
	)
	return err
}

const createMessageLinkPreview = `-- name: CreateMessageLinkPreview :exec

INSERT INTO message_link_previews (id, room_id, message_id, url, position, status, link_preview_id, removed_at, created_at)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9
)
`

type CreateMessageLinkPreviewParams struct {
	ID            ulid.ULID
	RoomID        ulid.ULID
	MessageID     ulid.ULID
	Url           string
	Position      int32
	Status        string
	LinkPreviewID *ulid.ULID
	RemovedAt     *time.Time
	Now           time.Time
}

// ---- メッセージに付いたプレビュー（message_link_previews）----
func (q *Queries) CreateMessageLinkPreview(ctx context.Context, arg CreateMessageLinkPreviewParams) error {
	_, err := q.db.Exec(ctx, createMessageLinkPreview,
		arg.ID,
		arg.RoomID,
		arg.MessageID,
		arg.Url,
		arg.Position,
		arg.Status,
		arg.LinkPreviewID,
		arg.RemovedAt,
		arg.Now,
	)
	return err
}

const deleteLinkPreviews = `-- name: DeleteLinkPreviews :exec
DELETE FROM link_previews
 WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteLinkPreviews(ctx context.Context, ids []ulid.ULID) error {
	_, err := q.db.Exec(ctx, deleteLinkPreviews, ids)
	return err
}

const deleteMessageLinkPreviews = `-- name: DeleteMessageLinkPreviews :exec
DELETE FROM message_link_previews
 WHERE message_id = $1
`

// メッセージを削除したとき。tombstone にカードは要らない（決定 10）。指していた結果は掃除のジョブが消す。
func (q *Queries) DeleteMessageLinkPreviews(ctx context.Context, messageID ulid.ULID) error {
	_, err := q.db.Exec(ctx, deleteMessageLinkPreviews, messageID)
	return err
}

const deleteMessageLinkPreviewsExcept = `-- name: DeleteMessageLinkPreviewsExcept :exec
DELETE FROM message_link_previews
 WHERE message_id = $1
   AND removed_at IS NULL
   AND NOT (url = ANY($2::text[]))
`

type DeleteMessageLinkPreviewsExceptParams struct {
	MessageID ulid.ULID
	Urls      []string
}

// 編集で本文から無くなった URL の行を消す。本人が消した行は残す（書き戻しても出さないため。決定 4）。
func (q *Queries) DeleteMessageLinkPreviewsExcept(ctx context.Context, arg DeleteMessageLinkPreviewsExceptParams) error {
	_, err := q.db.Exec(ctx, deleteMessageLinkPreviewsExcept, arg.MessageID, arg.Urls)
	return err
}

const enqueueStorageDeletions = `-- name: EnqueueStorageDeletions :exec
INSERT INTO storage_deletions (object_key, not_before, created_at)
SELECT unnest($1::text[]), $2::timestamptz, $3::timestamptz
ON CONFLICT (object_key) DO NOTHING
`

type EnqueueStorageDeletionsParams struct {
	ObjectKeys []string
	NotBefore  time.Time
	Now        time.Time
}

// 消した結果の画像とアイコンのオブジェクトを、ストレージの掃除の列に積む（ADR 0059 決定 6 の列を使う）。
func (q *Queries) EnqueueStorageDeletions(ctx context.Context, arg EnqueueStorageDeletionsParams) error {
	_, err := q.db.Exec(ctx, enqueueStorageDeletions, arg.ObjectKeys, arg.NotBefore, arg.Now)
	return err
}

const findFreshLinkPreview = `-- name: FindFreshLinkPreview :one


SELECT id, url, status, title, description, site_name, image_object_key, image_content_type, image_width, image_height, icon_object_key, icon_content_type, fetched_at
  FROM link_previews
 WHERE url = $1
   AND fetched_at >= $2::timestamptz
 ORDER BY fetched_at DESC
 LIMIT 1
   FOR KEY SHARE
`

type FindFreshLinkPreviewParams struct {
	Url   string
	Since time.Time
}

// 外部のリンクのプレビュー（ADR 0065）。
// ---- URL ごとの取得の結果（link_previews）----
// この URL の since より新しい取得の結果（決定 2 の 30 分の使い回し）。失敗も返す（取り直さない）。
// FOR KEY SHARE で、これを指す行を足すまでの間に掃除のジョブが消さないようにする（掃除は SKIP LOCKED で飛ばす）。
func (q *Queries) FindFreshLinkPreview(ctx context.Context, arg FindFreshLinkPreviewParams) (LinkPreview, error) {
	row := q.db.QueryRow(ctx, findFreshLinkPreview, arg.Url, arg.Since)
	var i LinkPreview
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Status,
		&i.Title,
		&i.Description,
		&i.SiteName,
		&i.ImageObjectKey,
		&i.ImageContentType,
		&i.ImageWidth,
		&i.ImageHeight,
		&i.IconObjectKey,
		&i.IconContentType,
		&i.FetchedAt,
	)
	return i, err
}

const getMessageLinkPreviewForUpdate = `-- name: GetMessageLinkPreviewForUpdate :one
SELECT id, room_id, message_id, url, position, status, link_preview_id, attempts, claimed_until, removed_at, created_at
  FROM message_link_previews
 WHERE id = $1
   AND message_id = $2
   FOR UPDATE
`

type GetMessageLinkPreviewForUpdateParams struct {
	ID        ulid.ULID
	MessageID ulid.ULID
}

// 取得の結果を書く前・本人が消す前に行をロックする。メッセージの行をロックしてから取る（編集と同じ順序）。
func (q *Queries) GetMessageLinkPreviewForUpdate(ctx context.Context, arg GetMessageLinkPreviewForUpdateParams) (MessageLinkPreview, error) {
	row := q.db.QueryRow(ctx, getMessageLinkPreviewForUpdate, arg.ID, arg.MessageID)
	var i MessageLinkPreview
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.MessageID,
		&i.Url,
		&i.Position,
		&i.Status,
		&i.LinkPreviewID,
		&i.Attempts,
		&i.ClaimedUntil,
		&i.RemovedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageLinkPreviewObjects = `-- name: GetMessageLinkPreviewObjects :one
SELECT lp.image_object_key,
       lp.image_content_type,
       lp.icon_object_key,
       lp.icon_content_type
  FROM message_link_previews m
  JOIN link_previews lp ON lp.id = m.link_preview_id
  JOIN messages msg ON msg.room_id = m.room_id AND msg.id = m.message_id
 WHERE m.room_id = $1
   AND m.message_id = $2
   AND m.id = $3
   AND m.status = 'ok'
   AND m.removed_at IS NULL
   AND msg.deleted_at IS NULL
`

type GetMessageLinkPreviewObjectsParams struct {
	RoomID    ulid.ULID
	MessageID ulid.ULID
	ID        ulid.ULID
}

type GetMessageLinkPreviewObjectsRow struct {
	ImageObjectKey   *string
	ImageContentType *string
	IconObjectKey    *string
	IconContentType  *string
}

// 見せているプレビューの画像とアイコンのオブジェクト（決定 7 の URL の API）。削除済みのメッセージのものは返さない。
func (q *Queries) GetMessageLinkPreviewObjects(ctx context.Context, arg GetMessageLinkPreviewObjectsParams) (GetMessageLinkPreviewObjectsRow, error) {
	row := q.db.QueryRow(ctx, getMessageLinkPreviewObjects, arg.RoomID, arg.MessageID, arg.ID)
	var i GetMessageLinkPreviewObjectsRow
	err := row.Scan(
		&i.ImageObjectKey,
		&i.ImageContentType,
		&i.IconObjectKey,
		&i.IconContentType,
	)
	return i, err
}

const listMessageLinkPreviewURLs = `-- name: ListMessageLinkPreviewURLs :many
SELECT url, removed_at
  FROM message_link_previews
 WHERE message_id = $1
`

type ListMessageLinkPreviewURLsRow struct {
	Url       string
	RemovedAt *time.Time
}

// 編集のときに、いまある行（消したものも含む）を読む（決定 4）。
func (q *Queries) ListMessageLinkPreviewURLs(ctx context.Context, messageID ulid.ULID) ([]ListMessageLinkPreviewURLsRow, error) {
	rows, err := q.db.Query(ctx, listMessageLinkPreviewURLs, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessageLinkPreviewURLsRow{}
	for rows.Next() {
		var i ListMessageLinkPreviewURLsRow
		if err := rows.Scan(&i.Url, &i.RemovedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageLinkPreviews = `-- name: ListMessageLinkPreviews :many
SELECT m.id,
       m.message_id,
       m.url,
       lp.site_name,
       lp.title,
       lp.description,
       lp.image_width,
       lp.image_height,
       (lp.icon_object_key IS NOT NULL)::bool AS has_icon
  FROM message_link_previews m
  JOIN link_previews lp ON lp.id = m.link_preview_id
 WHERE m.room_id = $1
   AND m.message_id = ANY($2::uuid[])
   AND m.status = 'ok'
   AND m.removed_at IS NULL
 ORDER BY m.message_id, m.position
`

type ListMessageLinkPreviewsParams struct {
	RoomID     ulid.ULID
	MessageIds []ulid.ULID
}

type ListMessageLinkPreviewsRow struct {
	ID          ulid.ULID
	MessageID   ulid.ULID
	Url         string
	SiteName    string
	Title       string
	Description string
	ImageWidth  *int32
	ImageHeight *int32
	HasIcon     bool
}

// ページの全メッセージの、見せるプレビューを 1 回で読む（N+1 にしない）。取得待ち・失敗・消したものは返さない（決定 6）。
func (q *Queries) ListMessageLinkPreviews(ctx context.Context, arg ListMessageLinkPreviewsParams) ([]ListMessageLinkPreviewsRow, error) {
	rows, err := q.db.Query(ctx, listMessageLinkPreviews, arg.RoomID, arg.MessageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessageLinkPreviewsRow{}
	for rows.Next() {
		var i ListMessageLinkPreviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Url,
			&i.SiteName,
			&i.Title,
			&i.Description,
			&i.ImageWidth,
			&i.ImageHeight,
			&i.HasIcon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUnreferencedLinkPreviews = `-- name: LockUnreferencedLinkPreviews :many
SELECT id, image_object_key, icon_object_key
  FROM link_previews lp
 WHERE fetched_at < $1::timestamptz
   AND NOT EXISTS (SELECT 1 FROM message_link_previews m WHERE m.link_preview_id = lp.id)
 ORDER BY fetched_at
 LIMIT $2
   FOR UPDATE SKIP LOCKED
`

type LockUnreferencedLinkPreviewsParams struct {
	Before  time.Time
	MaxRows int32
}

type LockUnreferencedLinkPreviewsRow struct {
	ID             ulid.ULID
	ImageObjectKey *string
	IconObjectKey  *string
}

// どのメッセージからも指されていない、before より古い結果を行ロックして取る（掃除。決定 10）。
// 使い回しの 30 分より十分に長い before を渡し、送信が指そうとしている行を消さないようにする。
func (q *Queries) LockUnreferencedLinkPreviews(ctx context.Context, arg LockUnreferencedLinkPreviewsParams) ([]LockUnreferencedLinkPreviewsRow, error) {
	rows, err := q.db.Query(ctx, lockUnreferencedLinkPreviews, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockUnreferencedLinkPreviewsRow{}
	for rows.Next() {
		var i LockUnreferencedLinkPreviewsRow
		if err := rows.Scan(&i.ID, &i.ImageObjectKey, &i.IconObjectKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMessageLinkPreview = `-- name: RemoveMessageLinkPreview :exec
UPDATE message_link_previews
   SET removed_at = $1::timestamptz
 WHERE id = $2
`

type RemoveMessageLinkPreviewParams struct {
	Now time.Time
	ID  ulid.ULID
}

// 本人が消した（決定 5）。行は残す。
func (q *Queries) RemoveMessageLinkPreview(ctx context.Context, arg RemoveMessageLinkPreviewParams) error {
	_, err := q.db.Exec(ctx, removeMessageLinkPreview, arg.Now, arg.ID)
	return err
}

const updateMessageLinkPreviewPositions = `-- name: UpdateMessageLinkPreviewPositions :exec
UPDATE message_link_previews m
   SET position = v.position
  FROM (SELECT unnest($2::text[]) AS url, unnest($3::int[]) AS position) AS v
 WHERE m.message_id = $1
   AND m.url = v.url
`

type UpdateMessageLinkPreviewPositionsParams struct {
	MessageID ulid.ULID
	Urls      []string
	Positions []int32
}

// 編集で URL の並びが変わったときに、並びだけを直す（取り直さない。決定 4）。
func (q *Queries) UpdateMessageLinkPreviewPositions(ctx context.Context, arg UpdateMessageLinkPreviewPositionsParams) error {
	_, err := q.db.Exec(ctx, updateMessageLinkPreviewPositions, arg.MessageID, arg.Urls, arg.Positions)
	return err
}
