// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mentions.sql

package store

import (
	"context"
	"time"

	ulid "github.com/oklog/ulid/v2"
)

const countRoomMentions = `-- name: CountRoomMentions :one
SELECT count(*)::bigint
  FROM message_mentions mm
  JOIN messages m ON m.room_id = mm.room_id AND m.id = mm.message_id
  JOIN room_members rm ON rm.room_id = mm.room_id AND rm.user_id = $1
  -- スレッドだけの返信は、チャンネルの既読位置では判定できない（ADR 0036）。自分のスレッドの既読位置と比べる。
  LEFT JOIN thread_members tm ON tm.thread_root_id = m.thread_root_id AND tm.user_id = $1
 WHERE mm.room_id = $2
   -- user_id が NULL の行は @channel（ルームの全員）。rm を JOIN しているので、メンバーでなければ数えない。
   AND (mm.user_id IS NULL OR mm.user_id = $1)
   AND CASE WHEN m.in_channel THEN m.user_seq > rm.last_read_user_seq
            ELSE tm.user_id IS NOT NULL AND m.thread_seq > tm.last_read_thread_seq
       END
`

type CountRoomMentionsParams struct {
	UserID ulid.ULID
	RoomID ulid.ULID
}

// 1 つのルームの、自分宛ての未読のメンションの数。既読の更新（ADR 0041）で使う。
// 条件は ListRoomsForUser / GetRoomSummary の相関サブクエリと同じ。片方だけ直さないこと。
func (q *Queries) CountRoomMentions(ctx context.Context, arg CountRoomMentionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRoomMentions, arg.UserID, arg.RoomID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createChannelMention = `-- name: CreateChannelMention :exec
INSERT INTO message_mentions (room_id, message_id, user_id, kind, created_at)
VALUES ($1, $2, NULL, 'channel', $3)
    ON CONFLICT DO NOTHING
`

type CreateChannelMentionParams struct {
	RoomID    ulid.ULID
	MessageID ulid.ULID
	Now       time.Time
}

// @channel は 1 行だけ。user_id が NULL で「ルームの全員」を表すので、ルームの人数によらず書き込みは 1 行で済む。
func (q *Queries) CreateChannelMention(ctx context.Context, arg CreateChannelMentionParams) error {
	_, err := q.db.Exec(ctx, createChannelMention, arg.RoomID, arg.MessageID, arg.Now)
	return err
}

const createUserMentions = `-- name: CreateUserMentions :execrows
INSERT INTO message_mentions (room_id, message_id, user_id, kind, created_at)
SELECT $1, $2, rm.user_id, $3, $4
  FROM room_members rm
 WHERE rm.room_id = $1
   AND rm.user_id = ANY($5::uuid[])
    ON CONFLICT DO NOTHING
`

type CreateUserMentionsParams struct {
	RoomID    ulid.ULID
	MessageID ulid.ULID
	Kind      string
	Now       time.Time
	UserIds   []ulid.ULID
}

// 個人へのメンション（kind = 'user'）と @here の解決結果（kind = 'here'）を入れる。
// room_members を JOIN するので、ルームのメンバーでない人の行はできない（知らせない。ADR 0041）。
// FK に任せて弾くとトランザクションごと落ちるので、ここで静かに落とす。
// 同じ人が @here と個人の両方で挙がったときは、先に入れた方（個人）が残る。
func (q *Queries) CreateUserMentions(ctx context.Context, arg CreateUserMentionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, createUserMentions,
		arg.RoomID,
		arg.MessageID,
		arg.Kind,
		arg.Now,
		arg.UserIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMessageMentions = `-- name: DeleteMessageMentions :exec

DELETE FROM message_mentions
 WHERE room_id = $1
   AND message_id = $2
`

type DeleteMessageMentionsParams struct {
	RoomID    ulid.ULID
	MessageID ulid.ULID
}

// メンション（ADR 0041）。
//
// 行は常に本文と一致させる。送信・編集・削除のたびに、そのメッセージの行を消してから入れ直す。
// 件数は数えるときに「既読位置より後の行」を数える（カウンタの列は持たない）。数える条件はルームの一覧にも書いてある（rooms.sql）。
// 本文が変わる前に、そのメッセージの行を消す。編集・削除のたびに呼ぶ。
func (q *Queries) DeleteMessageMentions(ctx context.Context, arg DeleteMessageMentionsParams) error {
	_, err := q.db.Exec(ctx, deleteMessageMentions, arg.RoomID, arg.MessageID)
	return err
}
