// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package store

import (
	"context"
	"time"

	ulid "github.com/oklog/ulid/v2"
)

const advanceLastReadSeq = `-- name: AdvanceLastReadSeq :one
UPDATE room_members rm
   SET last_read_seq = GREATEST(rm.last_read_seq, LEAST($1::bigint, r.last_message_seq))
  FROM rooms r
 WHERE r.id = rm.room_id
   AND rm.room_id = $2
   AND rm.user_id = $3
RETURNING rm.last_read_seq, r.last_message_seq
`

type AdvanceLastReadSeqParams struct {
	Seq    int64
	RoomID ulid.ULID
	UserID ulid.ULID
}

type AdvanceLastReadSeqRow struct {
	LastReadSeq    int64
	LastMessageSeq int64
}

// 既読位置を進める。後退させず、ルームの最新の seq を超えさせない。
// 送信者の既読（送信の直後）と、POST /rooms/{id}/read の両方で使う。ルームのメンバーでなければ行を返さない。
func (q *Queries) AdvanceLastReadSeq(ctx context.Context, arg AdvanceLastReadSeqParams) (AdvanceLastReadSeqRow, error) {
	row := q.db.QueryRow(ctx, advanceLastReadSeq, arg.Seq, arg.RoomID, arg.UserID)
	var i AdvanceLastReadSeqRow
	err := row.Scan(&i.LastReadSeq, &i.LastMessageSeq)
	return i, err
}

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (id, room_id, seq, sender_id, client_msg_id, body, reply_to_id, created_at)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8::timestamptz)
`

type CreateMessageParams struct {
	ID          ulid.ULID
	RoomID      ulid.ULID
	Seq         int64
	SenderID    ulid.ULID
	ClientMsgID ulid.ULID
	Body        string
	ReplyToID   *ulid.ULID
	Now         time.Time
}

// 返信先が別のルームのメッセージなら、複合 FK（messages_reply_to_fkey）の違反になる。
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.Exec(ctx, createMessage,
		arg.ID,
		arg.RoomID,
		arg.Seq,
		arg.SenderID,
		arg.ClientMsgID,
		arg.Body,
		arg.ReplyToID,
		arg.Now,
	)
	return err
}

const getMessageForUpdate = `-- name: GetMessageForUpdate :one
SELECT id, room_id, seq, sender_id, client_msg_id, body, reply_to_id, created_at, edited_at, deleted_at
  FROM messages
 WHERE room_id = $1
   AND id = $2
   FOR UPDATE
`

type GetMessageForUpdateParams struct {
	RoomID ulid.ULID
	ID     ulid.ULID
}

// 編集・削除の対象を行ロックする。room_id を条件に含め、別のルームの ID では見つからないようにする。
func (q *Queries) GetMessageForUpdate(ctx context.Context, arg GetMessageForUpdateParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageForUpdate, arg.RoomID, arg.ID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Seq,
		&i.SenderID,
		&i.ClientMsgID,
		&i.Body,
		&i.ReplyToID,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMessageIDByClientMsgID = `-- name: GetMessageIDByClientMsgID :one
SELECT id
  FROM messages
 WHERE room_id = $1
   AND sender_id = $2
   AND client_msg_id = $3
`

type GetMessageIDByClientMsgIDParams struct {
	RoomID      ulid.ULID
	SenderID    ulid.ULID
	ClientMsgID ulid.ULID
}

// 冪等な再送の検出。sender_id を条件に含めるので、他人の client_msg_id では引けない。
func (q *Queries) GetMessageIDByClientMsgID(ctx context.Context, arg GetMessageIDByClientMsgIDParams) (ulid.ULID, error) {
	row := q.db.QueryRow(ctx, getMessageIDByClientMsgID, arg.RoomID, arg.SenderID, arg.ClientMsgID)
	var id ulid.ULID
	err := row.Scan(&id)
	return id, err
}

const getMessageSenderID = `-- name: GetMessageSenderID :one
SELECT sender_id
  FROM messages
 WHERE room_id = $1
   AND id = $2
`

type GetMessageSenderIDParams struct {
	RoomID ulid.ULID
	ID     ulid.ULID
}

// 削除の判定に送信者のロールが必要なので、ロックを取る前に送信者を読む。sender_id は変わらないので、ロックの前に読んでよい。
func (q *Queries) GetMessageSenderID(ctx context.Context, arg GetMessageSenderIDParams) (ulid.ULID, error) {
	row := q.db.QueryRow(ctx, getMessageSenderID, arg.RoomID, arg.ID)
	var sender_id ulid.ULID
	err := row.Scan(&sender_id)
	return sender_id, err
}

const getMessageView = `-- name: GetMessageView :one
SELECT m.id, m.room_id, m.seq, m.sender_id, m.client_msg_id, m.body, m.reply_to_id,
       m.created_at, m.edited_at, m.deleted_at,
       u.handle AS sender_handle, u.display_name AS sender_display_name,
       p.seq AS reply_seq, p.sender_id AS reply_sender_id, p.body AS reply_body, p.deleted_at AS reply_deleted_at,
       pu.handle AS reply_sender_handle, pu.display_name AS reply_sender_display_name
  FROM messages m
  JOIN users u ON u.id = m.sender_id
  LEFT JOIN messages p ON p.room_id = m.room_id AND p.id = m.reply_to_id
  LEFT JOIN users pu ON pu.id = p.sender_id
 WHERE m.room_id = $1
   AND m.id = $2
`

type GetMessageViewParams struct {
	RoomID ulid.ULID
	ID     ulid.ULID
}

type GetMessageViewRow struct {
	ID                     ulid.ULID
	RoomID                 ulid.ULID
	Seq                    int64
	SenderID               ulid.ULID
	ClientMsgID            ulid.ULID
	Body                   string
	ReplyToID              *ulid.ULID
	CreatedAt              time.Time
	EditedAt               *time.Time
	DeletedAt              *time.Time
	SenderHandle           string
	SenderDisplayName      string
	ReplySeq               *int64
	ReplySenderID          *ulid.ULID
	ReplyBody              *string
	ReplyDeletedAt         *time.Time
	ReplySenderHandle      *string
	ReplySenderDisplayName *string
}

func (q *Queries) GetMessageView(ctx context.Context, arg GetMessageViewParams) (GetMessageViewRow, error) {
	row := q.db.QueryRow(ctx, getMessageView, arg.RoomID, arg.ID)
	var i GetMessageViewRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Seq,
		&i.SenderID,
		&i.ClientMsgID,
		&i.Body,
		&i.ReplyToID,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
		&i.SenderHandle,
		&i.SenderDisplayName,
		&i.ReplySeq,
		&i.ReplySenderID,
		&i.ReplyBody,
		&i.ReplyDeletedAt,
		&i.ReplySenderHandle,
		&i.ReplySenderDisplayName,
	)
	return i, err
}

const listMessagesAfter = `-- name: ListMessagesAfter :many
SELECT m.id, m.room_id, m.seq, m.sender_id, m.client_msg_id, m.body, m.reply_to_id,
       m.created_at, m.edited_at, m.deleted_at,
       u.handle AS sender_handle, u.display_name AS sender_display_name,
       p.seq AS reply_seq, p.sender_id AS reply_sender_id, p.body AS reply_body, p.deleted_at AS reply_deleted_at,
       pu.handle AS reply_sender_handle, pu.display_name AS reply_sender_display_name
  FROM messages m
  JOIN users u ON u.id = m.sender_id
  LEFT JOIN messages p ON p.room_id = m.room_id AND p.id = m.reply_to_id
  LEFT JOIN users pu ON pu.id = p.sender_id
 WHERE m.room_id = $1
   AND m.seq > $2
 ORDER BY m.seq
 LIMIT $3
`

type ListMessagesAfterParams struct {
	RoomID   ulid.ULID
	AfterSeq int64
	MaxRows  int32
}

type ListMessagesAfterRow struct {
	ID                     ulid.ULID
	RoomID                 ulid.ULID
	Seq                    int64
	SenderID               ulid.ULID
	ClientMsgID            ulid.ULID
	Body                   string
	ReplyToID              *ulid.ULID
	CreatedAt              time.Time
	EditedAt               *time.Time
	DeletedAt              *time.Time
	SenderHandle           string
	SenderDisplayName      string
	ReplySeq               *int64
	ReplySenderID          *ulid.ULID
	ReplyBody              *string
	ReplyDeletedAt         *time.Time
	ReplySenderHandle      *string
	ReplySenderDisplayName *string
}

// seq が after_seq より大きいメッセージを、古い順に max_rows 件。再接続の差分取得（ADR 0004）。
// 同じインデックスを逆方向に走査する。
func (q *Queries) ListMessagesAfter(ctx context.Context, arg ListMessagesAfterParams) ([]ListMessagesAfterRow, error) {
	rows, err := q.db.Query(ctx, listMessagesAfter, arg.RoomID, arg.AfterSeq, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesAfterRow{}
	for rows.Next() {
		var i ListMessagesAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Seq,
			&i.SenderID,
			&i.ClientMsgID,
			&i.Body,
			&i.ReplyToID,
			&i.CreatedAt,
			&i.EditedAt,
			&i.DeletedAt,
			&i.SenderHandle,
			&i.SenderDisplayName,
			&i.ReplySeq,
			&i.ReplySenderID,
			&i.ReplyBody,
			&i.ReplyDeletedAt,
			&i.ReplySenderHandle,
			&i.ReplySenderDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBefore = `-- name: ListMessagesBefore :many
SELECT m.id, m.room_id, m.seq, m.sender_id, m.client_msg_id, m.body, m.reply_to_id,
       m.created_at, m.edited_at, m.deleted_at,
       u.handle AS sender_handle, u.display_name AS sender_display_name,
       p.seq AS reply_seq, p.sender_id AS reply_sender_id, p.body AS reply_body, p.deleted_at AS reply_deleted_at,
       pu.handle AS reply_sender_handle, pu.display_name AS reply_sender_display_name
  FROM messages m
  JOIN users u ON u.id = m.sender_id
  LEFT JOIN messages p ON p.room_id = m.room_id AND p.id = m.reply_to_id
  LEFT JOIN users pu ON pu.id = p.sender_id
 WHERE m.room_id = $1
   AND m.seq < $2
 ORDER BY m.seq DESC
 LIMIT $3
`

type ListMessagesBeforeParams struct {
	RoomID    ulid.ULID
	BeforeSeq int64
	MaxRows   int32
}

type ListMessagesBeforeRow struct {
	ID                     ulid.ULID
	RoomID                 ulid.ULID
	Seq                    int64
	SenderID               ulid.ULID
	ClientMsgID            ulid.ULID
	Body                   string
	ReplyToID              *ulid.ULID
	CreatedAt              time.Time
	EditedAt               *time.Time
	DeletedAt              *time.Time
	SenderHandle           string
	SenderDisplayName      string
	ReplySeq               *int64
	ReplySenderID          *ulid.ULID
	ReplyBody              *string
	ReplyDeletedAt         *time.Time
	ReplySenderHandle      *string
	ReplySenderDisplayName *string
}

// seq が before_seq より小さいメッセージを、新しい順に max_rows 件。最新のページは before_seq に最大値を渡す。
// 「before_seq が NULL なら条件なし」とは書かない。汎用の実行計画でインデックスの範囲条件にならず、ルームの全件を走査しうるため。
// インデックス messages_room_id_seq_idx (room_id, seq DESC) を順方向に走査する。
func (q *Queries) ListMessagesBefore(ctx context.Context, arg ListMessagesBeforeParams) ([]ListMessagesBeforeRow, error) {
	rows, err := q.db.Query(ctx, listMessagesBefore, arg.RoomID, arg.BeforeSeq, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesBeforeRow{}
	for rows.Next() {
		var i ListMessagesBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Seq,
			&i.SenderID,
			&i.ClientMsgID,
			&i.Body,
			&i.ReplyToID,
			&i.CreatedAt,
			&i.EditedAt,
			&i.DeletedAt,
			&i.SenderHandle,
			&i.SenderDisplayName,
			&i.ReplySeq,
			&i.ReplySenderID,
			&i.ReplyBody,
			&i.ReplyDeletedAt,
			&i.ReplySenderHandle,
			&i.ReplySenderDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRoomMemberships = `-- name: LockRoomMemberships :many

SELECT user_id
  FROM room_members
 WHERE room_id = $1
   AND user_id = ANY($2::uuid[])
 ORDER BY user_id
   FOR NO KEY UPDATE
`

type LockRoomMembershipsParams struct {
	RoomID  ulid.ULID
	UserIds []ulid.ULID
}

// メッセージ（ADR 0002 / 0004 / 0012）。
//
// 一覧と 1 件の取得は、送信者と返信先のプレビューを同じ文で JOIN する（N+1 にしない）。
// sqlc は SELECT の列リストを共有できないので、GetMessageView / ListMessagesBefore / ListMessagesAfter の列は揃えて書く。
// user_ids のうちルームのメンバーである人の行を、FOR NO KEY UPDATE でロックして返す（ADR 0012）。
// 送信は同じトランザクションで last_read_seq を更新するので、その UPDATE と同じ強さのロックを先に取る。
// FOR SHARE で読んでから UPDATE すると、同じ人の並行した送信が互いの共有ロックを待ってデッドロックする。
func (q *Queries) LockRoomMemberships(ctx context.Context, arg LockRoomMembershipsParams) ([]ulid.ULID, error) {
	rows, err := q.db.Query(ctx, lockRoomMemberships, arg.RoomID, arg.UserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ulid.ULID{}
	for rows.Next() {
		var user_id ulid.ULID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMessage = `-- name: SoftDeleteMessage :exec
UPDATE messages
   SET body       = '',
       deleted_at = $1::timestamptz
 WHERE id = $2
`

type SoftDeleteMessageParams struct {
	Now time.Time
	ID  ulid.ULID
}

// 論理削除。行と seq は残し、本文だけを消す（ADR 0002 / 0004）。
func (q *Queries) SoftDeleteMessage(ctx context.Context, arg SoftDeleteMessageParams) error {
	_, err := q.db.Exec(ctx, softDeleteMessage, arg.Now, arg.ID)
	return err
}

const updateMessageBody = `-- name: UpdateMessageBody :exec
UPDATE messages
   SET body      = $1,
       edited_at = $2::timestamptz
 WHERE id = $3
`

type UpdateMessageBodyParams struct {
	Body string
	Now  time.Time
	ID   ulid.ULID
}

func (q *Queries) UpdateMessageBody(ctx context.Context, arg UpdateMessageBodyParams) error {
	_, err := q.db.Exec(ctx, updateMessageBody, arg.Body, arg.Now, arg.ID)
	return err
}
