// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	ulid "github.com/oklog/ulid/v2"
)

type Attachment struct {
	ID         ulid.ULID
	RoomID     ulid.ULID
	UploaderID ulid.ULID
	MessageID  *ulid.ULID
	Status     string
	ObjectKey  string
	MimeType   string
	SizeBytes  int64
	Width      *int32
	Height     *int32
	CreatedAt  time.Time
	FileName   string
}

type Message struct {
	ID          ulid.ULID
	RoomID      ulid.ULID
	Seq         int64
	SenderID    ulid.ULID
	ClientMsgID ulid.ULID
	Body        string
	ReplyToID   *ulid.ULID
	CreatedAt   time.Time
	EditedAt    *time.Time
	DeletedAt   *time.Time
}

type Room struct {
	ID             ulid.ULID
	WorkspaceID    ulid.ULID
	Kind           string
	Name           *string
	DmKey          *string
	IsDefault      bool
	CreatedBy      ulid.ULID
	LastMessageSeq int64
	LastMessageAt  *time.Time
	CreatedAt      time.Time
	ArchivedAt     *time.Time
}

type Workspace struct {
	ID           ulid.ULID
	Slug         string
	Name         string
	InvitePolicy string
	CreatedBy    ulid.ULID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    *time.Time
}

type WorkspaceInvite struct {
	ID          ulid.ULID
	WorkspaceID ulid.ULID
	CodeHash    []byte
	CreatedBy   ulid.ULID
	MaxUses     *int32
	UseCount    int32
	ExpiresAt   time.Time
	RevokedAt   *time.Time
	CreatedAt   time.Time
}
