// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	ulid "github.com/oklog/ulid/v2"
)

type Workspace struct {
	ID           ulid.ULID
	Slug         string
	Name         string
	InvitePolicy string
	CreatedBy    ulid.ULID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    *time.Time
}

type WorkspaceInvite struct {
	ID          ulid.ULID
	WorkspaceID ulid.ULID
	CodeHash    []byte
	CreatedBy   ulid.ULID
	MaxUses     *int32
	UseCount    int32
	ExpiresAt   time.Time
	RevokedAt   *time.Time
	CreatedAt   time.Time
}
