// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package store

import (
	"context"
	"time"

	ulid "github.com/oklog/ulid/v2"
)

const getWorkspaceNotifyLevel = `-- name: GetWorkspaceNotifyLevel :one

SELECT notify_level
  FROM workspace_members
 WHERE workspace_id = $1 AND user_id = $2
`

type GetWorkspaceNotifyLevelParams struct {
	WorkspaceID ulid.ULID
	UserID      ulid.ULID
}

// ミュートと通知の設定（ADR 0055）。
// 全体の「通知する内容」。行がなければメンバーではない（呼び出し側が 404 にする）。NULL は未設定。
func (q *Queries) GetWorkspaceNotifyLevel(ctx context.Context, arg GetWorkspaceNotifyLevelParams) (*string, error) {
	row := q.db.QueryRow(ctx, getWorkspaceNotifyLevel, arg.WorkspaceID, arg.UserID)
	var notify_level *string
	err := row.Scan(&notify_level)
	return notify_level, err
}

const setRoomNotifications = `-- name: SetRoomNotifications :one
UPDATE room_members
   SET notify_level = $1,
       muted        = $2,
       muted_until  = $3
 WHERE room_id = $4 AND user_id = $5
RETURNING notify_level, muted, muted_until
`

type SetRoomNotificationsParams struct {
	NotifyLevel *string
	Muted       bool
	MutedUntil  *time.Time
	RoomID      ulid.ULID
	UserID      ulid.ULID
}

type SetRoomNotificationsRow struct {
	NotifyLevel *string
	Muted       bool
	MutedUntil  *time.Time
}

// チャンネルごとの設定を全部の値で置き換える（PUT。決定 4）。組み合わせの検証はサービスで済ませてから呼ぶ。
// 行がなければメンバーではない（判定の後にルームから外された。呼び出し側が 403 にする）。
func (q *Queries) SetRoomNotifications(ctx context.Context, arg SetRoomNotificationsParams) (SetRoomNotificationsRow, error) {
	row := q.db.QueryRow(ctx, setRoomNotifications,
		arg.NotifyLevel,
		arg.Muted,
		arg.MutedUntil,
		arg.RoomID,
		arg.UserID,
	)
	var i SetRoomNotificationsRow
	err := row.Scan(&i.NotifyLevel, &i.Muted, &i.MutedUntil)
	return i, err
}

const setWorkspaceNotifyLevel = `-- name: SetWorkspaceNotifyLevel :one
UPDATE workspace_members
   SET notify_level = $1
 WHERE workspace_id = $2 AND user_id = $3
RETURNING notify_level
`

type SetWorkspaceNotifyLevelParams struct {
	NotifyLevel *string
	WorkspaceID ulid.ULID
	UserID      ulid.ULID
}

// 行がなければメンバーではない（呼び出し側が 404 にする）。
func (q *Queries) SetWorkspaceNotifyLevel(ctx context.Context, arg SetWorkspaceNotifyLevelParams) (*string, error) {
	row := q.db.QueryRow(ctx, setWorkspaceNotifyLevel, arg.NotifyLevel, arg.WorkspaceID, arg.UserID)
	var notify_level *string
	err := row.Scan(&notify_level)
	return notify_level, err
}
