// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pins.sql

package store

import (
	"context"
	"time"

	ulid "github.com/oklog/ulid/v2"
)

const countRoomPins = `-- name: CountRoomPins :one
SELECT count(*)
  FROM messages
 WHERE room_id = $1
   AND pinned_at IS NOT NULL
`

// 上限（100 件）の確認。rooms の行ロック（change_seq の採番）を持ったまま数えるので、同じルームの並行したピン留めと取り合わない（決定 4）。
func (q *Queries) CountRoomPins(ctx context.Context, roomID ulid.ULID) (int64, error) {
	row := q.db.QueryRow(ctx, countRoomPins, roomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listRoomPins = `-- name: ListRoomPins :many
SELECT m.id, m.room_id, m.seq, m.change_seq, m.user_seq, m.sender_id, m.client_msg_id, m.body,
       m.kind, m.system_type, m.system_data,
       m.thread_root_id, m.thread_seq, m.in_channel, m.last_thread_seq, m.thread_reply_count, m.thread_last_reply_at,
       m.created_at, m.edited_at, m.deleted_at,
       u.handle AS sender_handle, u.display_name AS sender_display_name,
       m.pinned_at, m.pinned_by, pu.handle AS pinned_by_handle, pu.display_name AS pinned_by_display_name
  FROM messages m
  JOIN users u ON u.id = m.sender_id
  LEFT JOIN users pu ON pu.id = m.pinned_by
 WHERE m.room_id = $1
   AND m.pinned_at IS NOT NULL
 ORDER BY m.pinned_at DESC, m.id DESC
 LIMIT $2
`

type ListRoomPinsParams struct {
	RoomID  ulid.ULID
	MaxRows int32
}

type ListRoomPinsRow struct {
	ID                  ulid.ULID
	RoomID              ulid.ULID
	Seq                 int64
	ChangeSeq           int64
	UserSeq             int64
	SenderID            ulid.ULID
	ClientMsgID         ulid.ULID
	Body                string
	Kind                string
	SystemType          *string
	SystemData          []byte
	ThreadRootID        *ulid.ULID
	ThreadSeq           *int64
	InChannel           bool
	LastThreadSeq       int64
	ThreadReplyCount    int32
	ThreadLastReplyAt   *time.Time
	CreatedAt           time.Time
	EditedAt            *time.Time
	DeletedAt           *time.Time
	SenderHandle        string
	SenderDisplayName   string
	PinnedAt            *time.Time
	PinnedBy            *ulid.ULID
	PinnedByHandle      *string
	PinnedByDisplayName *string
}

// ピン留めした時刻の新しい順（決定 5）。同じ時刻ならメッセージの ID で順を決める。上限が 100 件なのでページングしない。
// 列は GetMessageView と同じにして、Message への変換を共有する。
func (q *Queries) ListRoomPins(ctx context.Context, arg ListRoomPinsParams) ([]ListRoomPinsRow, error) {
	rows, err := q.db.Query(ctx, listRoomPins, arg.RoomID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomPinsRow{}
	for rows.Next() {
		var i ListRoomPinsRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Seq,
			&i.ChangeSeq,
			&i.UserSeq,
			&i.SenderID,
			&i.ClientMsgID,
			&i.Body,
			&i.Kind,
			&i.SystemType,
			&i.SystemData,
			&i.ThreadRootID,
			&i.ThreadSeq,
			&i.InChannel,
			&i.LastThreadSeq,
			&i.ThreadReplyCount,
			&i.ThreadLastReplyAt,
			&i.CreatedAt,
			&i.EditedAt,
			&i.DeletedAt,
			&i.SenderHandle,
			&i.SenderDisplayName,
			&i.PinnedAt,
			&i.PinnedBy,
			&i.PinnedByHandle,
			&i.PinnedByDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pinMessage = `-- name: PinMessage :execrows

UPDATE messages
   SET pinned_at  = $1::timestamptz,
       pinned_by  = $2,
       change_seq = $3
 WHERE id = $4
   AND pinned_at IS NULL
`

type PinMessageParams struct {
	Now       time.Time
	PinnedBy  *ulid.ULID
	ChangeSeq int64
	ID        ulid.ULID
}

// ピン留め（ADR 0054）。
// まだピン留めされていないときだけ付ける。0 行なら「すでにピン留め済み」で、番号も配信も使わない（冪等。決定 2）。
func (q *Queries) PinMessage(ctx context.Context, arg PinMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, pinMessage,
		arg.Now,
		arg.PinnedBy,
		arg.ChangeSeq,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unpinMessage = `-- name: UnpinMessage :execrows
UPDATE messages
   SET pinned_at  = NULL,
       pinned_by  = NULL,
       change_seq = $1
 WHERE id = $2
   AND pinned_at IS NOT NULL
`

type UnpinMessageParams struct {
	ChangeSeq int64
	ID        ulid.ULID
}

func (q *Queries) UnpinMessage(ctx context.Context, arg UnpinMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, unpinMessage, arg.ChangeSeq, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
