// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: presence.sql

package store

import (
	"context"
	"time"

	ulid "github.com/oklog/ulid/v2"
)

const clearMemberStatus = `-- name: ClearMemberStatus :execrows
UPDATE workspace_members
   SET status_emoji      = NULL,
       status_text       = NULL,
       status_expires_at = NULL
 WHERE workspace_id = $1
   AND user_id = $2
`

type ClearMemberStatusParams struct {
	WorkspaceID ulid.ULID
	UserID      ulid.ULID
}

// 解除する。設定していなくても成功（冪等）。ワークスペースのメンバーでなければ 0 行。
func (q *Queries) ClearMemberStatus(ctx context.Context, arg ClearMemberStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearMemberStatus, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getManualAway = `-- name: GetManualAway :one
SELECT manual_away FROM user_presence_settings WHERE user_id = $1
`

// 本人の設定を読む。行が無ければ false（呼ぶ側が pgx.ErrNoRows を false として扱う）。
func (q *Queries) GetManualAway(ctx context.Context, userID ulid.ULID) (bool, error) {
	row := q.db.QueryRow(ctx, getManualAway, userID)
	var manual_away bool
	err := row.Scan(&manual_away)
	return manual_away, err
}

const getMemberStatus = `-- name: GetMemberStatus :one
SELECT status_emoji, status_text, status_expires_at
  FROM workspace_members
 WHERE workspace_id = $1
   AND user_id = $2
`

type GetMemberStatusParams struct {
	WorkspaceID ulid.ULID
	UserID      ulid.ULID
}

type GetMemberStatusRow struct {
	StatusEmoji     *string
	StatusText      *string
	StatusExpiresAt *time.Time
}

// 1 人ぶんのステータス（イベントに載せる値を、書いた直後に読み直すのに使う）。
func (q *Queries) GetMemberStatus(ctx context.Context, arg GetMemberStatusParams) (GetMemberStatusRow, error) {
	row := q.db.QueryRow(ctx, getMemberStatus, arg.WorkspaceID, arg.UserID)
	var i GetMemberStatusRow
	err := row.Scan(&i.StatusEmoji, &i.StatusText, &i.StatusExpiresAt)
	return i, err
}

const setManualAway = `-- name: SetManualAway :exec

INSERT INTO user_presence_settings (user_id, manual_away, updated_at)
VALUES ($1, $2, $3)
    ON CONFLICT (user_id) DO UPDATE
    SET manual_away = EXCLUDED.manual_away,
        updated_at  = EXCLUDED.updated_at
`

type SetManualAwayParams struct {
	UserID     ulid.ULID
	ManualAway bool
	Now        time.Time
}

// 離席とカスタムステータス（ADR 0049）。
//
// ここにあるのは「本人が選んだ設定」だけ。自動で決まる presence は Redis にあり、DB には来ない。
// 期限切れのステータスを落とすのは、読み取りの変換（internal/chat の statusOf）1 箇所だけ（ADR 0049 決定 6 の追記）。
// SQL の CASE で落とす案は、sqlc が式の型と NULL 可能性を推せず、`interface{}` か「NULL にならない string」になってしまうため。
// 手動の離席を設定する。設定したときだけ行を作り、以降は上書きする（冪等）。
func (q *Queries) SetManualAway(ctx context.Context, arg SetManualAwayParams) error {
	_, err := q.db.Exec(ctx, setManualAway, arg.UserID, arg.ManualAway, arg.Now)
	return err
}

const setMemberStatus = `-- name: SetMemberStatus :one
UPDATE workspace_members
   SET status_emoji      = $1,
       status_text       = $2,
       status_expires_at = $3
 WHERE workspace_id = $4
   AND user_id = $5
RETURNING status_emoji, status_text, status_expires_at
`

type SetMemberStatusParams struct {
	StatusEmoji     *string
	StatusText      *string
	StatusExpiresAt *time.Time
	WorkspaceID     ulid.ULID
	UserID          ulid.ULID
}

type SetMemberStatusRow struct {
	StatusEmoji     *string
	StatusText      *string
	StatusExpiresAt *time.Time
}

// カスタムステータスを設定する。ワークスペースのメンバーでなければ 0 行（呼ぶ側が ErrNotFound にする）。
func (q *Queries) SetMemberStatus(ctx context.Context, arg SetMemberStatusParams) (SetMemberStatusRow, error) {
	row := q.db.QueryRow(ctx, setMemberStatus,
		arg.StatusEmoji,
		arg.StatusText,
		arg.StatusExpiresAt,
		arg.WorkspaceID,
		arg.UserID,
	)
	var i SetMemberStatusRow
	err := row.Scan(&i.StatusEmoji, &i.StatusText, &i.StatusExpiresAt)
	return i, err
}
