// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reactions.sql

package store

import (
	"context"
	"time"

	ulid "github.com/oklog/ulid/v2"
)

const addMessageReaction = `-- name: AddMessageReaction :execrows

INSERT INTO message_reactions (room_id, message_id, user_id, emoji, created_at)
VALUES ($1, $2, $3, $4, $5)
    ON CONFLICT DO NOTHING
`

type AddMessageReactionParams struct {
	RoomID    ulid.ULID
	MessageID ulid.ULID
	UserID    ulid.ULID
	Emoji     string
	Now       time.Time
}

// 絵文字のリアクション（ADR 0044）。
//
// 行を積むだけで、件数のカウンタは持たない。数も「誰が付けたか」も、読むときに数え直す。
// 付け外しの冪等性は主キー（message_id, user_id, emoji）が保証するので、
// アプリ側で「すでに付いているか」を確かめてから書く、という往復は要らない。
// 付ける。すでに付いていれば 0 行。呼ぶ側は「0 行なら change_seq を進めない」で冪等にできる（ADR 0044 決定 2）。
func (q *Queries) AddMessageReaction(ctx context.Context, arg AddMessageReactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, addMessageReaction,
		arg.RoomID,
		arg.MessageID,
		arg.UserID,
		arg.Emoji,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countMessageReactionKinds = `-- name: CountMessageReactionKinds :one
SELECT count(DISTINCT emoji)::bigint
  FROM message_reactions
 WHERE message_id = $1
`

// そのメッセージに付いている絵文字の種類の数。20 種類の上限（ADR 0044 決定 5）の判定に使う。
// 付ける直前に、そのメッセージの行を FOR UPDATE で押さえた上で数える（同時に 21 種類目が入らないように）。
func (q *Queries) CountMessageReactionKinds(ctx context.Context, messageID ulid.ULID) (int64, error) {
	row := q.db.QueryRow(ctx, countMessageReactionKinds, messageID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listMessageReactions = `-- name: ListMessageReactions :many
SELECT mr.message_id,
       mr.emoji,
       count(*)::bigint                                                    AS reaction_count,
       bool_or(mr.user_id = $1)                              AS reacted_by_viewer,
       (array_agg(mr.user_id ORDER BY mr.created_at, mr.user_id))[1:8]::uuid[] AS user_ids
  FROM message_reactions mr
 WHERE mr.room_id = $2
   AND mr.message_id = ANY($3::uuid[])
 GROUP BY mr.message_id, mr.emoji
 ORDER BY mr.message_id, min(mr.created_at), mr.emoji
`

type ListMessageReactionsParams struct {
	Viewer     ulid.ULID
	RoomID     ulid.ULID
	MessageIds []ulid.ULID
}

type ListMessageReactionsRow struct {
	MessageID       ulid.ULID
	Emoji           string
	ReactionCount   int64
	ReactedByViewer bool
	UserIds         []ulid.ULID
}

// ページの全メッセージのリアクションを、1 回で絵文字ごとに集計する（N+1 にしない）。
//
// 並びは「最初に付いた順」（MIN(created_at)）。数が増減しても入れ替わらない（ADR 0044 決定 3）。
// users は先頭 8 人まで。全員を載せるとレスポンスが人数ぶん膨らむので、ホバーに要る数だけにする。
// me は「受け取る人ごとの値」なので REST でしか使わない。WebSocket の配信では捨てる（ADR 0044 決定 3 の追記）。
func (q *Queries) ListMessageReactions(ctx context.Context, arg ListMessageReactionsParams) ([]ListMessageReactionsRow, error) {
	rows, err := q.db.Query(ctx, listMessageReactions, arg.Viewer, arg.RoomID, arg.MessageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessageReactionsRow{}
	for rows.Next() {
		var i ListMessageReactionsRow
		if err := rows.Scan(
			&i.MessageID,
			&i.Emoji,
			&i.ReactionCount,
			&i.ReactedByViewer,
			&i.UserIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messageReactionKindExists = `-- name: MessageReactionKindExists :one
SELECT EXISTS (
    SELECT 1 FROM message_reactions
     WHERE message_id = $1
       AND emoji = $2
)
`

type MessageReactionKindExistsParams struct {
	MessageID ulid.ULID
	Emoji     string
}

// その絵文字がすでにそのメッセージに付いているか。種類の上限に達していても、
// 「すでにある絵文字をもう 1 人が押す」のは種類が増えないので通すために使う。
func (q *Queries) MessageReactionKindExists(ctx context.Context, arg MessageReactionKindExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, messageReactionKindExists, arg.MessageID, arg.Emoji)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeMessageReaction = `-- name: RemoveMessageReaction :execrows
DELETE FROM message_reactions
 WHERE message_id = $1
   AND user_id = $2
   AND emoji = $3
`

type RemoveMessageReactionParams struct {
	MessageID ulid.ULID
	UserID    ulid.ULID
	Emoji     string
}

// 外す。付いていなければ 0 行。
func (q *Queries) RemoveMessageReaction(ctx context.Context, arg RemoveMessageReactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeMessageReaction, arg.MessageID, arg.UserID, arg.Emoji)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMessageChangeSeq = `-- name: UpdateMessageChangeSeq :exec
UPDATE messages
   SET change_seq = $1
 WHERE id = $2
`

type UpdateMessageChangeSeqParams struct {
	ChangeSeq int64
	ID        ulid.ULID
}

// 本文を変えずに change_seq だけを進める（リアクションの付け外し。ADR 0044 決定 2）。
// edited_at は触らない。リアクションは「編集」ではないので、（編集済み）を付けてはいけない。
func (q *Queries) UpdateMessageChangeSeq(ctx context.Context, arg UpdateMessageChangeSeqParams) error {
	_, err := q.db.Exec(ctx, updateMessageChangeSeq, arg.ChangeSeq, arg.ID)
	return err
}
