// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package store

import (
	"context"
	"time"

	ulid "github.com/oklog/ulid/v2"
)

const allocateMessageSeq = `-- name: AllocateMessageSeq :one
UPDATE rooms
   SET last_message_seq = last_message_seq + 1,
       last_message_at  = $1::timestamptz
 WHERE id = $2
RETURNING last_message_seq
`

type AllocateMessageSeqParams struct {
	Now    time.Time
	RoomID ulid.ULID
}

// ルームの次の seq を採番して返す（ADR 0002「採番方式の確定」）。
// 送信と同じトランザクションの中で呼ぶ。rooms の行ロックで同じルームへの送信が直列化され、
// ロールバックすれば採番も取り消されるので欠番にならない。
func (q *Queries) AllocateMessageSeq(ctx context.Context, arg AllocateMessageSeqParams) (int64, error) {
	row := q.db.QueryRow(ctx, allocateMessageSeq, arg.Now, arg.RoomID)
	var last_message_seq int64
	err := row.Scan(&last_message_seq)
	return last_message_seq, err
}
