// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package store

import (
	"context"
	"time"

	ulid "github.com/oklog/ulid/v2"
)

const addRoomMember = `-- name: AddRoomMember :execrows
INSERT INTO room_members (room_id, user_id, last_read_seq, last_read_user_seq, joined_at)
SELECT r.id, $1, r.last_message_seq, r.last_user_seq, $2::timestamptz
  FROM rooms r
 WHERE r.id = $3
ON CONFLICT DO NOTHING
`

type AddRoomMemberParams struct {
	UserID ulid.ULID
	Now    time.Time
	RoomID ulid.ULID
}

// ルームに参加する。すでにメンバーなら何もせず 0 を返す（冪等）。
// last_read_seq / last_read_user_seq は同じ文の中で rooms から読み、参加前のメッセージを未読にしない。
func (q *Queries) AddRoomMember(ctx context.Context, arg AddRoomMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, addRoomMember, arg.UserID, arg.Now, arg.RoomID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const allocateChangeSeq = `-- name: AllocateChangeSeq :one
UPDATE rooms
   SET last_change_seq = last_change_seq + $1::bigint
 WHERE id = $2
RETURNING last_change_seq
`

type AllocateChangeSeqParams struct {
	N      int64
	RoomID ulid.ULID
}

// 既存のメッセージの編集・削除のために change_seq だけを n 個採番し、最後の番号を返す（ADR 0014）。seq は進めない。
// 返信の削除は、返信と親（返信数が減る）の 2 つを使う（ADR 0036）。
func (q *Queries) AllocateChangeSeq(ctx context.Context, arg AllocateChangeSeqParams) (int64, error) {
	row := q.db.QueryRow(ctx, allocateChangeSeq, arg.N, arg.RoomID)
	var last_change_seq int64
	err := row.Scan(&last_change_seq)
	return last_change_seq, err
}

const allocateMessageSeq = `-- name: AllocateMessageSeq :one

UPDATE rooms
   SET last_message_seq = last_message_seq + 1,
       last_change_seq  = last_change_seq + 1,
       last_user_seq    = last_user_seq + 1,
       last_message_at  = $1::timestamptz
 WHERE id = $2
RETURNING last_message_seq, last_change_seq, last_user_seq
`

type AllocateMessageSeqParams struct {
	Now    time.Time
	RoomID ulid.ULID
}

type AllocateMessageSeqRow struct {
	LastMessageSeq int64
	LastChangeSeq  int64
	LastUserSeq    int64
}

// ルーム（ADR 0006 / 0011）。
// ルームの次の seq と change_seq を採番して返す（ADR 0002「採番方式の確定」/ ADR 0014）。
// 送信と同じトランザクションの中で呼ぶ。rooms の行ロックで同じルームへの送信・編集・削除が直列化され、
// ロールバックすれば採番も取り消されるので欠番にならない。
// 人の発言なので user_seq も 1 進める（ADR 0033）。
func (q *Queries) AllocateMessageSeq(ctx context.Context, arg AllocateMessageSeqParams) (AllocateMessageSeqRow, error) {
	row := q.db.QueryRow(ctx, allocateMessageSeq, arg.Now, arg.RoomID)
	var i AllocateMessageSeqRow
	err := row.Scan(&i.LastMessageSeq, &i.LastChangeSeq, &i.LastUserSeq)
	return i, err
}

const allocateSystemMessageSeq = `-- name: AllocateSystemMessageSeq :one
UPDATE rooms
   SET last_message_seq = last_message_seq + 1,
       last_change_seq  = last_change_seq + 1,
       last_message_at  = $1::timestamptz
 WHERE id = $2
RETURNING last_message_seq, last_change_seq, last_user_seq
`

type AllocateSystemMessageSeqParams struct {
	Now    time.Time
	RoomID ulid.ULID
}

type AllocateSystemMessageSeqRow struct {
	LastMessageSeq int64
	LastChangeSeq  int64
	LastUserSeq    int64
}

// システムメッセージ（ADR 0033）の採番。seq と change_seq は進め、user_seq は進めない（未読数に数えない）。
func (q *Queries) AllocateSystemMessageSeq(ctx context.Context, arg AllocateSystemMessageSeqParams) (AllocateSystemMessageSeqRow, error) {
	row := q.db.QueryRow(ctx, allocateSystemMessageSeq, arg.Now, arg.RoomID)
	var i AllocateSystemMessageSeqRow
	err := row.Scan(&i.LastMessageSeq, &i.LastChangeSeq, &i.LastUserSeq)
	return i, err
}

const allocateThreadReplySeq = `-- name: AllocateThreadReplySeq :one
UPDATE rooms
   SET last_message_seq = last_message_seq + 1,
       last_change_seq  = last_change_seq + 2,
       last_user_seq    = last_user_seq + CASE WHEN $1::boolean THEN 1 ELSE 0 END,
       last_message_at  = CASE WHEN $1::boolean THEN $2::timestamptz ELSE last_message_at END
 WHERE id = $3
RETURNING last_message_seq, last_change_seq, last_user_seq
`

type AllocateThreadReplySeqParams struct {
	InChannel bool
	Now       time.Time
	RoomID    ulid.ULID
}

type AllocateThreadReplySeqRow struct {
	LastMessageSeq int64
	LastChangeSeq  int64
	LastUserSeq    int64
}

// スレッドの返信の採番（ADR 0036）。seq はルームのものを 1 つ、change_seq は返信と親の 2 つ分を進める
// （返信は last_change_seq - 1、親は last_change_seq を使う）。
// スレッドだけの返信はチャンネルに出ないので、user_seq（チャンネルの未読）・last_message_at（サイドバーの並び）は進めない。
// 「チャンネルにも投稿する」（in_channel）の返信はチャンネルの発言として数え、どちらも進める（ADR 0039）。
func (q *Queries) AllocateThreadReplySeq(ctx context.Context, arg AllocateThreadReplySeqParams) (AllocateThreadReplySeqRow, error) {
	row := q.db.QueryRow(ctx, allocateThreadReplySeq, arg.InChannel, arg.Now, arg.RoomID)
	var i AllocateThreadReplySeqRow
	err := row.Scan(&i.LastMessageSeq, &i.LastChangeSeq, &i.LastUserSeq)
	return i, err
}

const createDMRoom = `-- name: CreateDMRoom :one
INSERT INTO rooms (id, workspace_id, kind, dm_key, created_by, created_at)
VALUES ($1, $2, 'dm', $3, $4, $5::timestamptz)
ON CONFLICT (workspace_id, dm_key) WHERE kind = 'dm' DO NOTHING
RETURNING id, workspace_id, kind, name, dm_key, is_default, created_by, last_message_seq, last_message_at, created_at, archived_at, last_change_seq, last_user_seq
`

type CreateDMRoomParams struct {
	ID          ulid.ULID
	WorkspaceID ulid.ULID
	DmKey       *string
	CreatedBy   ulid.ULID
	Now         time.Time
}

// DM を作る。同じ 2 人の DM がすでにあれば何もせず、行を返さない（呼び出し側で既存を読む）。
// 並行して同じ DM を作ると、2 本目は 1 本目の UNIQUE の確定を待ってから DO NOTHING になる。
func (q *Queries) CreateDMRoom(ctx context.Context, arg CreateDMRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createDMRoom,
		arg.ID,
		arg.WorkspaceID,
		arg.DmKey,
		arg.CreatedBy,
		arg.Now,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Name,
		&i.DmKey,
		&i.IsDefault,
		&i.CreatedBy,
		&i.LastMessageSeq,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.LastChangeSeq,
		&i.LastUserSeq,
	)
	return i, err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (id, workspace_id, kind, name, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6::timestamptz)
RETURNING id, workspace_id, kind, name, dm_key, is_default, created_by, last_message_seq, last_message_at, created_at, archived_at, last_change_seq, last_user_seq
`

type CreateRoomParams struct {
	ID          ulid.ULID
	WorkspaceID ulid.ULID
	Kind        string
	Name        *string
	CreatedBy   ulid.ULID
	Now         time.Time
}

// public / private のルーム。名前の重複は部分 UNIQUE インデックス（rooms_workspace_id_name_idx）で検出する。
func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.ID,
		arg.WorkspaceID,
		arg.Kind,
		arg.Name,
		arg.CreatedBy,
		arg.Now,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Name,
		&i.DmKey,
		&i.IsDefault,
		&i.CreatedBy,
		&i.LastMessageSeq,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.LastChangeSeq,
		&i.LastUserSeq,
	)
	return i, err
}

const deleteRoomMember = `-- name: DeleteRoomMember :execrows
DELETE FROM room_members
 WHERE room_id = $1
   AND user_id = $2
`

type DeleteRoomMemberParams struct {
	RoomID ulid.ULID
	UserID ulid.ULID
}

func (q *Queries) DeleteRoomMember(ctx context.Context, arg DeleteRoomMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRoomMember, arg.RoomID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDMRoom = `-- name: GetDMRoom :one
SELECT id, workspace_id, kind, name, dm_key, is_default, created_by, last_message_seq, last_message_at, created_at, archived_at, last_change_seq, last_user_seq
  FROM rooms
 WHERE workspace_id = $1
   AND kind = 'dm'
   AND dm_key = $2
`

type GetDMRoomParams struct {
	WorkspaceID ulid.ULID
	DmKey       *string
}

func (q *Queries) GetDMRoom(ctx context.Context, arg GetDMRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, getDMRoom, arg.WorkspaceID, arg.DmKey)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Name,
		&i.DmKey,
		&i.IsDefault,
		&i.CreatedBy,
		&i.LastMessageSeq,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.LastChangeSeq,
		&i.LastUserSeq,
	)
	return i, err
}

const getRoom = `-- name: GetRoom :one
SELECT r.id, r.workspace_id, r.kind, r.name, r.dm_key, r.is_default, r.created_by, r.last_message_seq, r.last_message_at, r.created_at, r.archived_at, r.last_change_seq, r.last_user_seq
  FROM rooms r
  JOIN workspaces w ON w.id = r.workspace_id
 WHERE r.id = $1
   AND w.deleted_at IS NULL
`

// 削除済みのワークスペースのルームは見つからないものとして扱う。
func (q *Queries) GetRoom(ctx context.Context, id ulid.ULID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Name,
		&i.DmKey,
		&i.IsDefault,
		&i.CreatedBy,
		&i.LastMessageSeq,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.LastChangeSeq,
		&i.LastUserSeq,
	)
	return i, err
}

const getRoomMemberCount = `-- name: GetRoomMemberCount :one
SELECT count(*)
  FROM room_members
 WHERE room_id = $1
`

func (q *Queries) GetRoomMemberCount(ctx context.Context, roomID ulid.ULID) (int64, error) {
	row := q.db.QueryRow(ctx, getRoomMemberCount, roomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRoomMemberships = `-- name: GetRoomMemberships :many
SELECT user_id
  FROM room_members
 WHERE room_id = $1
   AND user_id = ANY($2::uuid[])
`

type GetRoomMembershipsParams struct {
	RoomID  ulid.ULID
	UserIds []ulid.ULID
}

// user_ids のうち、ルームのメンバーである人。
func (q *Queries) GetRoomMemberships(ctx context.Context, arg GetRoomMembershipsParams) ([]ulid.ULID, error) {
	rows, err := q.db.Query(ctx, getRoomMemberships, arg.RoomID, arg.UserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ulid.ULID{}
	for rows.Next() {
		var user_id ulid.ULID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomSummary = `-- name: GetRoomSummary :one
SELECT r.id, r.workspace_id, r.kind, r.name, r.dm_key, r.is_default, r.created_by, r.last_message_seq, r.last_message_at, r.created_at, r.archived_at, r.last_change_seq, r.last_user_seq, (rm.user_id IS NOT NULL)::boolean AS is_member, rm.last_read_seq, rm.last_read_user_seq,
       -- 自分宛ての未読のメンションの数（ADR 0041）。条件は CountRoomMentions（mentions.sql）と同じ。片方だけ直さないこと。
       -- 参加していない public ルームでは rm.user_id が NULL になるので 0 になる。
       (SELECT count(*) FROM message_mentions mm
          JOIN messages m ON m.room_id = mm.room_id AND m.id = mm.message_id
          LEFT JOIN thread_members tm ON tm.thread_root_id = m.thread_root_id AND tm.user_id = rm.user_id
         WHERE mm.room_id = r.id
           AND rm.user_id IS NOT NULL
           AND (mm.user_id IS NULL OR mm.user_id = rm.user_id)
           AND CASE WHEN m.in_channel THEN m.user_seq > rm.last_read_user_seq
                    ELSE tm.user_id IS NOT NULL AND m.thread_seq > tm.last_read_thread_seq
               END)::bigint AS mention_count,
       lm.id AS last_message_id, lm.sender_id AS last_message_sender_id, lm.body AS last_message_body,
       lm.kind AS last_message_kind, lm.system_type AS last_message_system_type,
       lm.system_data AS last_message_system_data,
       lm.created_at AS last_message_created_at, lm.deleted_at AS last_message_deleted_at,
       lu.handle AS last_message_sender_handle, lu.display_name AS last_message_sender_display_name
  FROM rooms r
  LEFT JOIN room_members rm ON rm.room_id = r.id AND rm.user_id = $1
  LEFT JOIN messages lm ON lm.room_id = r.id AND lm.seq = (
        SELECT max(m.seq) FROM messages m WHERE m.room_id = r.id AND m.in_channel AND m.deleted_at IS NULL)
  LEFT JOIN users lu ON lu.id = lm.sender_id
 WHERE r.id = $2
`

type GetRoomSummaryParams struct {
	UserID ulid.ULID
	RoomID ulid.ULID
}

type GetRoomSummaryRow struct {
	Room                         Room
	IsMember                     bool
	LastReadSeq                  *int64
	LastReadUserSeq              *int64
	MentionCount                 int64
	LastMessageID                *ulid.ULID
	LastMessageSenderID          *ulid.ULID
	LastMessageBody              *string
	LastMessageKind              *string
	LastMessageSystemType        *string
	LastMessageSystemData        []byte
	LastMessageCreatedAt         *time.Time
	LastMessageDeletedAt         *time.Time
	LastMessageSenderHandle      *string
	LastMessageSenderDisplayName *string
}

// 1 件のルームについて、ListRoomsForUser と同じ列（既読位置と最終メッセージ）を返す。読めるかどうかの判定は呼び出し側で済ませる。
func (q *Queries) GetRoomSummary(ctx context.Context, arg GetRoomSummaryParams) (GetRoomSummaryRow, error) {
	row := q.db.QueryRow(ctx, getRoomSummary, arg.UserID, arg.RoomID)
	var i GetRoomSummaryRow
	err := row.Scan(
		&i.Room.ID,
		&i.Room.WorkspaceID,
		&i.Room.Kind,
		&i.Room.Name,
		&i.Room.DmKey,
		&i.Room.IsDefault,
		&i.Room.CreatedBy,
		&i.Room.LastMessageSeq,
		&i.Room.LastMessageAt,
		&i.Room.CreatedAt,
		&i.Room.ArchivedAt,
		&i.Room.LastChangeSeq,
		&i.Room.LastUserSeq,
		&i.IsMember,
		&i.LastReadSeq,
		&i.LastReadUserSeq,
		&i.MentionCount,
		&i.LastMessageID,
		&i.LastMessageSenderID,
		&i.LastMessageBody,
		&i.LastMessageKind,
		&i.LastMessageSystemType,
		&i.LastMessageSystemData,
		&i.LastMessageCreatedAt,
		&i.LastMessageDeletedAt,
		&i.LastMessageSenderHandle,
		&i.LastMessageSenderDisplayName,
	)
	return i, err
}

const listRoomMemberIDs = `-- name: ListRoomMemberIDs :many
SELECT user_id
  FROM room_members
 WHERE room_id = $1
 ORDER BY user_id
`

// ルームのメンバーの user_id をすべて返す。@here の対象を presence に問い合わせるために使う（ADR 0041）。
// 表示用ではないので、ページングもプロフィールの JOIN もしない。
func (q *Queries) ListRoomMemberIDs(ctx context.Context, roomID ulid.ULID) ([]ulid.ULID, error) {
	rows, err := q.db.Query(ctx, listRoomMemberIDs, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ulid.ULID{}
	for rows.Next() {
		var user_id ulid.ULID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomMembers = `-- name: ListRoomMembers :many
SELECT rm.user_id, rm.joined_at, wm.role, u.handle, u.display_name,
       COALESCE(ps.manual_away, false)::boolean AS manual_away,
       wm.status_emoji, wm.status_text, wm.status_expires_at
  FROM room_members rm
  JOIN rooms r ON r.id = rm.room_id
  JOIN workspace_members wm ON wm.workspace_id = r.workspace_id AND wm.user_id = rm.user_id
  JOIN users u ON u.id = rm.user_id
  LEFT JOIN user_presence_settings ps ON ps.user_id = rm.user_id
 WHERE rm.room_id = $1
   AND rm.user_id > $2
   AND u.deleted_at IS NULL
 ORDER BY rm.user_id
 LIMIT $3
`

type ListRoomMembersParams struct {
	RoomID  ulid.ULID
	After   ulid.ULID
	MaxRows int32
}

type ListRoomMembersRow struct {
	UserID          ulid.ULID
	JoinedAt        time.Time
	Role            string
	Handle          string
	DisplayName     string
	ManualAway      bool
	StatusEmoji     *string
	StatusText      *string
	StatusExpiresAt *time.Time
}

// ルームのメンバーと、ワークスペースでのロール。主キー (room_id, user_id) の順に走査するので user_id をカーソルにする。
// 本人の設定（手動の離席とカスタムステータス。ADR 0049）も一緒に読む。期限切れのステータスはここで落とす。
func (q *Queries) ListRoomMembers(ctx context.Context, arg ListRoomMembersParams) ([]ListRoomMembersRow, error) {
	rows, err := q.db.Query(ctx, listRoomMembers, arg.RoomID, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomMembersRow{}
	for rows.Next() {
		var i ListRoomMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.JoinedAt,
			&i.Role,
			&i.Handle,
			&i.DisplayName,
			&i.ManualAway,
			&i.StatusEmoji,
			&i.StatusText,
			&i.StatusExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsForUser = `-- name: ListRoomsForUser :many
SELECT r.id, r.workspace_id, r.kind, r.name, r.dm_key, r.is_default, r.created_by, r.last_message_seq, r.last_message_at, r.created_at, r.archived_at, r.last_change_seq, r.last_user_seq, (rm.user_id IS NOT NULL)::boolean AS is_member, rm.last_read_seq, rm.last_read_user_seq,
       -- 自分宛ての未読のメンションの数（ADR 0041）。条件は CountRoomMentions（mentions.sql）と同じ。片方だけ直さないこと。
       -- 参加していない public ルームでは rm.user_id が NULL になるので 0 になる。
       (SELECT count(*) FROM message_mentions mm
          JOIN messages m ON m.room_id = mm.room_id AND m.id = mm.message_id
          LEFT JOIN thread_members tm ON tm.thread_root_id = m.thread_root_id AND tm.user_id = rm.user_id
         WHERE mm.room_id = r.id
           AND rm.user_id IS NOT NULL
           AND (mm.user_id IS NULL OR mm.user_id = rm.user_id)
           AND CASE WHEN m.in_channel THEN m.user_seq > rm.last_read_user_seq
                    ELSE tm.user_id IS NOT NULL AND m.thread_seq > tm.last_read_thread_seq
               END)::bigint AS mention_count,
       lm.id AS last_message_id, lm.sender_id AS last_message_sender_id, lm.body AS last_message_body,
       lm.kind AS last_message_kind, lm.system_type AS last_message_system_type,
       lm.system_data AS last_message_system_data,
       lm.created_at AS last_message_created_at, lm.deleted_at AS last_message_deleted_at,
       lu.handle AS last_message_sender_handle, lu.display_name AS last_message_sender_display_name
  FROM rooms r
  LEFT JOIN room_members rm ON rm.room_id = r.id AND rm.user_id = $1
  LEFT JOIN messages lm ON lm.room_id = r.id AND lm.seq = (
        SELECT max(m.seq) FROM messages m WHERE m.room_id = r.id AND m.in_channel AND m.deleted_at IS NULL)
  LEFT JOIN users lu ON lu.id = lm.sender_id
 WHERE r.workspace_id = $2
   AND (r.kind = 'public' OR rm.user_id IS NOT NULL)
 ORDER BY r.last_message_at DESC NULLS LAST, r.id
`

type ListRoomsForUserParams struct {
	UserID      ulid.ULID
	WorkspaceID ulid.ULID
}

type ListRoomsForUserRow struct {
	Room                         Room
	IsMember                     bool
	LastReadSeq                  *int64
	LastReadUserSeq              *int64
	MentionCount                 int64
	LastMessageID                *ulid.ULID
	LastMessageSenderID          *ulid.ULID
	LastMessageBody              *string
	LastMessageKind              *string
	LastMessageSystemType        *string
	LastMessageSystemData        []byte
	LastMessageCreatedAt         *time.Time
	LastMessageDeletedAt         *time.Time
	LastMessageSenderHandle      *string
	LastMessageSenderDisplayName *string
}

// サイドバーのルーム一覧: 参加しているルーム（全種類）と、参加していない public ルーム。
// 読めない private / dm は含めない。並びは最近メッセージがあった順（インデックス rooms_workspace_id_last_message_at_idx）。
// 最終メッセージは「チャンネルに出ていて、削除されていない最後の行」（ADR 0038）。スレッドの返信（ADR 0036）と削除済みを飛ばす。
// その seq をルームごとの相関サブクエリ（max）で引く。Postgres は max を部分インデックス messages_room_id_channel_seq_idx の
// 新しい順の走査に置き換え、条件に合う最初の 1 行で止まる（1 文のクエリなので N+1 にはならない。ADR 0012）。
// 削除済みが続く分だけ多く読むが、削除はまれなので受け入れる。LATERAL で書かないのは、sqlc が列を NULL にならないものとして扱うため。
// 未読数はクライアントにも出せるよう last_read_seq をそのまま返し、サービスで last_user_seq との差を取る
// （システムメッセージは数えない。ADR 0033）。
func (q *Queries) ListRoomsForUser(ctx context.Context, arg ListRoomsForUserParams) ([]ListRoomsForUserRow, error) {
	rows, err := q.db.Query(ctx, listRoomsForUser, arg.UserID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomsForUserRow{}
	for rows.Next() {
		var i ListRoomsForUserRow
		if err := rows.Scan(
			&i.Room.ID,
			&i.Room.WorkspaceID,
			&i.Room.Kind,
			&i.Room.Name,
			&i.Room.DmKey,
			&i.Room.IsDefault,
			&i.Room.CreatedBy,
			&i.Room.LastMessageSeq,
			&i.Room.LastMessageAt,
			&i.Room.CreatedAt,
			&i.Room.ArchivedAt,
			&i.Room.LastChangeSeq,
			&i.Room.LastUserSeq,
			&i.IsMember,
			&i.LastReadSeq,
			&i.LastReadUserSeq,
			&i.MentionCount,
			&i.LastMessageID,
			&i.LastMessageSenderID,
			&i.LastMessageBody,
			&i.LastMessageKind,
			&i.LastMessageSystemType,
			&i.LastMessageSystemData,
			&i.LastMessageCreatedAt,
			&i.LastMessageDeletedAt,
			&i.LastMessageSenderHandle,
			&i.LastMessageSenderDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProfiles = `-- name: ListUserProfiles :many
SELECT id, handle, display_name
  FROM users
 WHERE id = ANY($1::uuid[])
`

type ListUserProfilesRow struct {
	ID          ulid.ULID
	Handle      string
	DisplayName string
}

// DM の相手などの公開プロフィールをまとめて引く（N+1 にしない）。退会済みでも匿名化した値を返す。
func (q *Queries) ListUserProfiles(ctx context.Context, ids []ulid.ULID) ([]ListUserProfilesRow, error) {
	rows, err := q.db.Query(ctx, listUserProfiles, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserProfilesRow{}
	for rows.Next() {
		var i ListUserProfilesRow
		if err := rows.Scan(&i.ID, &i.Handle, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms
   SET name       = coalesce($1, name),
       is_default = coalesce($2, is_default)
 WHERE id = $3
RETURNING id, workspace_id, kind, name, dm_key, is_default, created_by, last_message_seq, last_message_at, created_at, archived_at, last_change_seq, last_user_seq
`

type UpdateRoomParams struct {
	Name      *string
	IsDefault *bool
	ID        ulid.ULID
}

// NULL を渡した項目は変更しない（PATCH）。
func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoom, arg.Name, arg.IsDefault, arg.ID)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Name,
		&i.DmKey,
		&i.IsDefault,
		&i.CreatedBy,
		&i.LastMessageSeq,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.LastChangeSeq,
		&i.LastUserSeq,
	)
	return i, err
}
