// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saved.sql

package store

import (
	"context"
	"time"

	ulid "github.com/oklog/ulid/v2"
)

const allocateSavedChangeSeq = `-- name: AllocateSavedChangeSeq :one
UPDATE workspace_members
   SET last_saved_change_seq = last_saved_change_seq + 1
 WHERE workspace_id = $1
   AND user_id = $2
RETURNING last_saved_change_seq
`

type AllocateSavedChangeSeqParams struct {
	WorkspaceID ulid.ULID
	UserID      ulid.ULID
}

// 本人ごとの change_seq を 1 つ進める（ADR 0054 決定 7）。実際に状態が変わるときだけ呼ぶ。
func (q *Queries) AllocateSavedChangeSeq(ctx context.Context, arg AllocateSavedChangeSeqParams) (int64, error) {
	row := q.db.QueryRow(ctx, allocateSavedChangeSeq, arg.WorkspaceID, arg.UserID)
	var last_saved_change_seq int64
	err := row.Scan(&last_saved_change_seq)
	return last_saved_change_seq, err
}

const countSavedInProgress = `-- name: CountSavedInProgress :one
SELECT count(*)
  FROM saved_messages
 WHERE workspace_id = $1
   AND user_id = $2
   AND state = 'in_progress'
`

type CountSavedInProgressParams struct {
	WorkspaceID ulid.ULID
	UserID      ulid.ULID
}

// 「進行中」のタブの件数（決定 9）。読めなくなった行も数える（一覧に残るので、件数と行の数をそろえる）。
func (q *Queries) CountSavedInProgress(ctx context.Context, arg CountSavedInProgressParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSavedInProgress, arg.WorkspaceID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLastSavedChangeSeq = `-- name: GetLastSavedChangeSeq :one
SELECT last_saved_change_seq
  FROM workspace_members
 WHERE workspace_id = $1
   AND user_id = $2
`

type GetLastSavedChangeSeqParams struct {
	WorkspaceID ulid.ULID
	UserID      ulid.ULID
}

func (q *Queries) GetLastSavedChangeSeq(ctx context.Context, arg GetLastSavedChangeSeqParams) (int64, error) {
	row := q.db.QueryRow(ctx, getLastSavedChangeSeq, arg.WorkspaceID, arg.UserID)
	var last_saved_change_seq int64
	err := row.Scan(&last_saved_change_seq)
	return last_saved_change_seq, err
}

const getSavedMessage = `-- name: GetSavedMessage :one
SELECT workspace_id, user_id, message_id, room_id, id, state, change_seq, saved_at, updated_at
  FROM saved_messages
 WHERE user_id = $1
   AND message_id = $2
`

type GetSavedMessageParams struct {
	UserID    ulid.ULID
	MessageID ulid.ULID
}

func (q *Queries) GetSavedMessage(ctx context.Context, arg GetSavedMessageParams) (SavedMessage, error) {
	row := q.db.QueryRow(ctx, getSavedMessage, arg.UserID, arg.MessageID)
	var i SavedMessage
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.MessageID,
		&i.RoomID,
		&i.ID,
		&i.State,
		&i.ChangeSeq,
		&i.SavedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSavedMessage = `-- name: InsertSavedMessage :exec
INSERT INTO saved_messages (workspace_id, user_id, message_id, room_id, id, state, change_seq, saved_at, updated_at)
VALUES ($1, $2, $3, $4, $5,
        'in_progress', $6, $7::timestamptz, $7::timestamptz)
`

type InsertSavedMessageParams struct {
	WorkspaceID ulid.ULID
	UserID      ulid.ULID
	MessageID   ulid.ULID
	RoomID      ulid.ULID
	ID          ulid.ULID
	ChangeSeq   int64
	Now         time.Time
}

func (q *Queries) InsertSavedMessage(ctx context.Context, arg InsertSavedMessageParams) error {
	_, err := q.db.Exec(ctx, insertSavedMessage,
		arg.WorkspaceID,
		arg.UserID,
		arg.MessageID,
		arg.RoomID,
		arg.ID,
		arg.ChangeSeq,
		arg.Now,
	)
	return err
}

const listMessageViewsByIDs = `-- name: ListMessageViewsByIDs :many
SELECT m.id, m.room_id, m.seq, m.change_seq, m.user_seq, m.sender_id, m.client_msg_id, m.body,
       m.kind, m.system_type, m.system_data,
       m.thread_root_id, m.thread_seq, m.in_channel, m.last_thread_seq, m.thread_reply_count, m.thread_last_reply_at,
       m.created_at, m.edited_at, m.deleted_at,
       u.handle AS sender_handle, u.display_name AS sender_display_name,
       m.pinned_at, m.pinned_by, pu.handle AS pinned_by_handle, pu.display_name AS pinned_by_display_name
  FROM messages m
  JOIN users u ON u.id = m.sender_id
  LEFT JOIN users pu ON pu.id = m.pinned_by
 WHERE m.room_id = $1
   AND m.id = ANY($2::uuid[])
`

type ListMessageViewsByIDsParams struct {
	RoomID ulid.ULID
	Ids    []ulid.ULID
}

type ListMessageViewsByIDsRow struct {
	ID                  ulid.ULID
	RoomID              ulid.ULID
	Seq                 int64
	ChangeSeq           int64
	UserSeq             int64
	SenderID            ulid.ULID
	ClientMsgID         ulid.ULID
	Body                string
	Kind                string
	SystemType          *string
	SystemData          []byte
	ThreadRootID        *ulid.ULID
	ThreadSeq           *int64
	InChannel           bool
	LastThreadSeq       int64
	ThreadReplyCount    int32
	ThreadLastReplyAt   *time.Time
	CreatedAt           time.Time
	EditedAt            *time.Time
	DeletedAt           *time.Time
	SenderHandle        string
	SenderDisplayName   string
	PinnedAt            *time.Time
	PinnedBy            *ulid.ULID
	PinnedByHandle      *string
	PinnedByDisplayName *string
}

// 保存の一覧に載せるメッセージを、ルームごとにまとめて読む。列は GetMessageView と同じ。
func (q *Queries) ListMessageViewsByIDs(ctx context.Context, arg ListMessageViewsByIDsParams) ([]ListMessageViewsByIDsRow, error) {
	rows, err := q.db.Query(ctx, listMessageViewsByIDs, arg.RoomID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessageViewsByIDsRow{}
	for rows.Next() {
		var i ListMessageViewsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Seq,
			&i.ChangeSeq,
			&i.UserSeq,
			&i.SenderID,
			&i.ClientMsgID,
			&i.Body,
			&i.Kind,
			&i.SystemType,
			&i.SystemData,
			&i.ThreadRootID,
			&i.ThreadSeq,
			&i.InChannel,
			&i.LastThreadSeq,
			&i.ThreadReplyCount,
			&i.ThreadLastReplyAt,
			&i.CreatedAt,
			&i.EditedAt,
			&i.DeletedAt,
			&i.SenderHandle,
			&i.SenderDisplayName,
			&i.PinnedAt,
			&i.PinnedBy,
			&i.PinnedByHandle,
			&i.PinnedByDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedMessageIDs = `-- name: ListSavedMessageIDs :many
SELECT message_id
  FROM saved_messages
 WHERE user_id = $1
   AND message_id = ANY($2::uuid[])
   AND state <> 'removed'
`

type ListSavedMessageIDsParams struct {
	UserID     ulid.ULID
	MessageIds []ulid.ULID
}

// メッセージの「保存済み」の印（決定 10）。ページの全メッセージを 1 回で引く（N+1 にしない）。
func (q *Queries) ListSavedMessageIDs(ctx context.Context, arg ListSavedMessageIDsParams) ([]ulid.ULID, error) {
	rows, err := q.db.Query(ctx, listSavedMessageIDs, arg.UserID, arg.MessageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ulid.ULID{}
	for rows.Next() {
		var message_id ulid.ULID
		if err := rows.Scan(&message_id); err != nil {
			return nil, err
		}
		items = append(items, message_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedMessages = `-- name: ListSavedMessages :many
SELECT workspace_id, user_id, message_id, room_id, id, state, change_seq, saved_at, updated_at
  FROM saved_messages
 WHERE workspace_id = $1
   AND user_id = $2
   AND state = $3
   AND id < $4
 ORDER BY id DESC
 LIMIT $5
`

type ListSavedMessagesParams struct {
	WorkspaceID ulid.ULID
	UserID      ulid.ULID
	State       string
	BeforeID    ulid.ULID
	MaxRows     int32
}

// タブの一覧を保存した新しい順に max_rows 件。最初のページは before_id に最大の ID を渡す（カーソル。OFFSET を使わない）。
func (q *Queries) ListSavedMessages(ctx context.Context, arg ListSavedMessagesParams) ([]SavedMessage, error) {
	rows, err := q.db.Query(ctx, listSavedMessages,
		arg.WorkspaceID,
		arg.UserID,
		arg.State,
		arg.BeforeID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavedMessage{}
	for rows.Next() {
		var i SavedMessage
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.MessageID,
			&i.RoomID,
			&i.ID,
			&i.State,
			&i.ChangeSeq,
			&i.SavedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedMessagesChangedAfter = `-- name: ListSavedMessagesChangedAfter :many
SELECT workspace_id, user_id, message_id, room_id, id, state, change_seq, saved_at, updated_at
  FROM saved_messages
 WHERE workspace_id = $1
   AND user_id = $2
   AND change_seq > $3
 ORDER BY change_seq
 LIMIT $4
`

type ListSavedMessagesChangedAfterParams struct {
	WorkspaceID    ulid.ULID
	UserID         ulid.ULID
	AfterChangeSeq int64
	MaxRows        int32
}

// 再接続の差分（決定 7）。removed の行も返す（切断中に外されたものを消せるように）。
func (q *Queries) ListSavedMessagesChangedAfter(ctx context.Context, arg ListSavedMessagesChangedAfterParams) ([]SavedMessage, error) {
	rows, err := q.db.Query(ctx, listSavedMessagesChangedAfter,
		arg.WorkspaceID,
		arg.UserID,
		arg.AfterChangeSeq,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavedMessage{}
	for rows.Next() {
		var i SavedMessage
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.MessageID,
			&i.RoomID,
			&i.ID,
			&i.State,
			&i.ChangeSeq,
			&i.SavedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSavedCounter = `-- name: LockSavedCounter :one

SELECT last_saved_change_seq
  FROM workspace_members
 WHERE workspace_id = $1
   AND user_id = $2
   FOR NO KEY UPDATE
`

type LockSavedCounterParams struct {
	WorkspaceID ulid.ULID
	UserID      ulid.ULID
}

// 「後で」（自分用の保存。ADR 0054）。
// 本人の保存の変更を直列にする。同じ人の同時の変更（別のタブ）が、行の読み取りと採番の間に割り込まないようにする。
// キーは変えないので FOR NO KEY UPDATE（workspace_members への FK の KEY SHARE と取り合わない）。
// 0 行ならワークスペースのメンバーではない。
func (q *Queries) LockSavedCounter(ctx context.Context, arg LockSavedCounterParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockSavedCounter, arg.WorkspaceID, arg.UserID)
	var last_saved_change_seq int64
	err := row.Scan(&last_saved_change_seq)
	return last_saved_change_seq, err
}

const resaveSavedMessage = `-- name: ResaveSavedMessage :exec
UPDATE saved_messages
   SET id         = $1,
       state      = 'in_progress',
       change_seq = $2,
       saved_at   = $3::timestamptz,
       updated_at = $3::timestamptz
 WHERE user_id = $4
   AND message_id = $5
`

type ResaveSavedMessageParams struct {
	ID        ulid.ULID
	ChangeSeq int64
	Now       time.Time
	UserID    ulid.ULID
	MessageID ulid.ULID
}

// 外した行をもう一度保存した。同じ行を進行中に戻し、ID を振り直して一覧の先頭に出す（決定 6）。
func (q *Queries) ResaveSavedMessage(ctx context.Context, arg ResaveSavedMessageParams) error {
	_, err := q.db.Exec(ctx, resaveSavedMessage,
		arg.ID,
		arg.ChangeSeq,
		arg.Now,
		arg.UserID,
		arg.MessageID,
	)
	return err
}

const updateSavedMessageState = `-- name: UpdateSavedMessageState :exec
UPDATE saved_messages
   SET state      = $1,
       change_seq = $2,
       updated_at = $3::timestamptz
 WHERE user_id = $4
   AND message_id = $5
`

type UpdateSavedMessageStateParams struct {
	State     string
	ChangeSeq int64
	Now       time.Time
	UserID    ulid.ULID
	MessageID ulid.ULID
}

func (q *Queries) UpdateSavedMessageState(ctx context.Context, arg UpdateSavedMessageStateParams) error {
	_, err := q.db.Exec(ctx, updateSavedMessageState,
		arg.State,
		arg.ChangeSeq,
		arg.Now,
		arg.UserID,
		arg.MessageID,
	)
	return err
}
