// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package store

import (
	"context"
	"time"

	ulid "github.com/oklog/ulid/v2"
)

const searchMessages = `-- name: SearchMessages :many

WITH readable_rooms AS (
    SELECT r.id, r.kind, r.name, r.dm_key
      FROM rooms r
      LEFT JOIN room_members rm ON rm.room_id = r.id AND rm.user_id = $13
     WHERE r.workspace_id = $14
       AND (r.kind = 'public' OR rm.user_id IS NOT NULL)
)
SELECT m.id, m.room_id, m.seq, m.thread_root_id, m.in_channel, m.body, m.created_at, m.edited_at,
       m.sender_id, u.handle AS sender_handle, u.display_name AS sender_display_name,
       rr.kind AS room_kind, rr.name AS room_name, rr.dm_key AS room_dm_key,
       -- 添付の件数（画面の「添付 N 件」）。1 文の中の相関サブクエリなので N+1 にはならない。
       (SELECT count(*) FROM attachments a WHERE a.message_id = m.id AND a.status = 'attached')::bigint AS attachment_count
  FROM messages m
  JOIN readable_rooms rr ON rr.id = m.room_id
  JOIN users u ON u.id = m.sender_id
 -- 部分索引 messages_body_search_idx の述語と同じ形で書く。ここを緩めると索引が使えなくなる
 WHERE m.deleted_at IS NULL
   AND m.kind = 'user'
   AND lower(normalize(m.body, NFKC)) LIKE $1
   AND ($2::text[] IS NULL OR lower(normalize(m.body, NFKC)) LIKE ALL ($2::text[]))
   -- 除外（` + "`" + `-語` + "`" + `）。NOT LIKE は索引を引けないが、肯定の語が索引を引いたあとの絞り込みとして効く
   AND ($3::text[] IS NULL OR lower(normalize(m.body, NFKC)) NOT LIKE ALL ($3::text[]))
   AND ($4::uuid[] IS NULL OR m.room_id = ANY ($4::uuid[]))
   AND ($5::uuid[] IS NULL OR m.room_id <> ALL ($5::uuid[]))
   AND ($6::uuid[] IS NULL OR m.sender_id = ANY ($6::uuid[]))
   AND ($7::uuid[] IS NULL OR m.sender_id <> ALL ($7::uuid[]))
   AND ($8::timestamptz IS NULL OR m.created_at >= $8::timestamptz)
   AND ($9::timestamptz IS NULL OR m.created_at < $9::timestamptz)
   -- カーソル（決定 4）。最初のページは「どの行より新しい」も持たない値を渡す
   AND (m.created_at, m.id) < ($10::timestamptz, $11::uuid)
 ORDER BY m.created_at DESC, m.id DESC
 LIMIT $12
`

type SearchMessagesParams struct {
	Term             string
	MoreTerms        []string
	ExcludeTerms     []string
	RoomIds          []ulid.ULID
	ExcludeRoomIds   []ulid.ULID
	SenderIds        []ulid.ULID
	ExcludeSenderIds []ulid.ULID
	After            *time.Time
	Before           *time.Time
	BeforeAt         time.Time
	BeforeID         ulid.ULID
	MaxRows          int32
	UserID           ulid.ULID
	WorkspaceID      ulid.ULID
}

type SearchMessagesRow struct {
	ID                ulid.ULID
	RoomID            ulid.ULID
	Seq               int64
	ThreadRootID      *ulid.ULID
	InChannel         bool
	Body              string
	CreatedAt         time.Time
	EditedAt          *time.Time
	SenderID          ulid.ULID
	SenderHandle      string
	SenderDisplayName string
	RoomKind          string
	RoomName          *string
	RoomDmKey         *string
	AttachmentCount   int64
}

// メッセージの検索（ADR 0061）。
// 読める範囲のメッセージを、新しい順に 1 ページ返す。
//
// **本文の条件の書き方に決まりがある（ADR 0061 決定 6 / 2026-09-23 に実測）。**
//
//   - `term` は**必ず 1 つの `LIKE` として書く**。これが `messages_body_search_idx`（pg_bigm の 2-gram GIN）の
//     `Index Cond` になり、索引がこのクエリを引く。
//   - 2 つ目以降の語は `more_terms` にまとめ、`LIKE ALL(配列)` で再チェックする。
//     配列の形では 2-gram のキーが使われない（計画の `Index Cond` に入らず、部分索引の述語しか効かない）ので、
//     索引を引く語は 1 つに絞り、残りは絞り込みに回す。
//   - **同じ語を並べて固定のスロットを埋めない。** 同じ条件を 8 個並べると索引は引けるが、
//     選択率が掛け合わされて見積もりが壊れる（実測: 実際 939 行に対して `rows=1`）。計画の選び方を誤らせる。
//   - どの語を `term` にするかは呼ぶ側が決める（長い語ほど 2-gram のキーが多く、絞り込みが効く）。
//
// 認可は `readable_rooms` の 1 か所に集める（決定 3）。`authz.CanReadRoom` と同じ条件で、
// public はワークスペースのメンバーなら参加していなくても読め、private / dm はメンバーだけ。
// アーカイブしたルームは外さない（アーカイブは「書けない」であって「読めない」ではない。ADR 0059 決定 2）。
// **`authz.CanReadRoom` を変えたらここも直すこと**（`search_test.go` が同じ組み合わせを検査する）。
//
// 並びは新しい順だけ（決定 4）。ルームをまたぐので `seq` は使えず、同じ時刻は `id`（ULID）で決める。
func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error) {
	rows, err := q.db.Query(ctx, searchMessages,
		arg.Term,
		arg.MoreTerms,
		arg.ExcludeTerms,
		arg.RoomIds,
		arg.ExcludeRoomIds,
		arg.SenderIds,
		arg.ExcludeSenderIds,
		arg.After,
		arg.Before,
		arg.BeforeAt,
		arg.BeforeID,
		arg.MaxRows,
		arg.UserID,
		arg.WorkspaceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMessagesRow{}
	for rows.Next() {
		var i SearchMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Seq,
			&i.ThreadRootID,
			&i.InChannel,
			&i.Body,
			&i.CreatedAt,
			&i.EditedAt,
			&i.SenderID,
			&i.SenderHandle,
			&i.SenderDisplayName,
			&i.RoomKind,
			&i.RoomName,
			&i.RoomDmKey,
			&i.AttachmentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
