// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storage_deletions.sql

package store

import (
	"context"
	"time"
)

const deleteStorageDeletions = `-- name: DeleteStorageDeletions :exec
DELETE FROM storage_deletions
 WHERE object_key = ANY($1::text[])
`

func (q *Queries) DeleteStorageDeletions(ctx context.Context, objectKeys []string) error {
	_, err := q.db.Exec(ctx, deleteStorageDeletions, objectKeys)
	return err
}

const lockDueStorageDeletions = `-- name: LockDueStorageDeletions :many

SELECT object_key
  FROM storage_deletions
 WHERE not_before <= $1::timestamptz
 ORDER BY not_before
 LIMIT $2
   FOR UPDATE SKIP LOCKED
`

type LockDueStorageDeletionsParams struct {
	Now     time.Time
	MaxRows int32
}

// ストレージのオブジェクトの掃除の列（ADR 0059 決定 6）。
// not_before を過ぎた行を古い順に行ロックして取る。SKIP LOCKED で、複数台が同時に実行しても同じ行を取り合わない（添付の掃除と同じ）。
func (q *Queries) LockDueStorageDeletions(ctx context.Context, arg LockDueStorageDeletionsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, lockDueStorageDeletions, arg.Now, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var object_key string
		if err := rows.Scan(&object_key); err != nil {
			return nil, err
		}
		items = append(items, object_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
