// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package store

import (
	"context"

	ulid "github.com/oklog/ulid/v2"
)

const listRoomAccessForUser = `-- name: ListRoomAccessForUser :many

SELECT r.id, r.workspace_id, r.kind,
       coalesce(wm.role, '')::text AS role,
       (rm.user_id IS NOT NULL)::boolean AS is_room_member
  FROM rooms r
  JOIN workspaces w ON w.id = r.workspace_id AND w.deleted_at IS NULL
  LEFT JOIN workspace_members wm ON wm.workspace_id = r.workspace_id AND wm.user_id = $1
  LEFT JOIN room_members rm ON rm.room_id = r.id AND rm.user_id = $1
 WHERE r.id = ANY($2::uuid[])
`

type ListRoomAccessForUserParams struct {
	UserID  ulid.ULID
	RoomIds []ulid.ULID
}

type ListRoomAccessForUserRow struct {
	ID           ulid.ULID
	WorkspaceID  ulid.ULID
	Kind         string
	Role         string
	IsRoomMember bool
}

// WebSocket の購読の authz に必要な事実（ADR 0015）。判定そのものは authz の関数が行う。
// どれも読み取りだけで、ロックしない。購読と権限の変更の競合は Hub の epoch で扱う。
// room_ids のうち存在するルームについて、user_id のワークスペースでのロールとルームのメンバーかどうかを返す。
// 削除済みのワークスペースのルームは返さない（存在しないものとして扱う）。
func (q *Queries) ListRoomAccessForUser(ctx context.Context, arg ListRoomAccessForUserParams) ([]ListRoomAccessForUserRow, error) {
	rows, err := q.db.Query(ctx, listRoomAccessForUser, arg.UserID, arg.RoomIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomAccessForUserRow{}
	for rows.Next() {
		var i ListRoomAccessForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Kind,
			&i.Role,
			&i.IsRoomMember,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceIDsForUser = `-- name: ListWorkspaceIDsForUser :many
SELECT wm.workspace_id
  FROM workspace_members wm
  JOIN workspaces w ON w.id = wm.workspace_id AND w.deleted_at IS NULL
 WHERE wm.user_id = $1
`

// user_id が所属するすべてのワークスペース。presence.changed の宛先に使う。
func (q *Queries) ListWorkspaceIDsForUser(ctx context.Context, userID ulid.ULID) ([]ulid.ULID, error) {
	rows, err := q.db.Query(ctx, listWorkspaceIDsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ulid.ULID{}
	for rows.Next() {
		var workspace_id ulid.ULID
		if err := rows.Scan(&workspace_id); err != nil {
			return nil, err
		}
		items = append(items, workspace_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceRolesForUser = `-- name: ListWorkspaceRolesForUser :many
SELECT wm.workspace_id, wm.role
  FROM workspace_members wm
  JOIN workspaces w ON w.id = wm.workspace_id AND w.deleted_at IS NULL
 WHERE wm.user_id = $1
   AND wm.workspace_id = ANY($2::uuid[])
`

type ListWorkspaceRolesForUserParams struct {
	UserID       ulid.ULID
	WorkspaceIds []ulid.ULID
}

type ListWorkspaceRolesForUserRow struct {
	WorkspaceID ulid.ULID
	Role        string
}

// workspace_ids のうち、user_id がメンバーであるワークスペースとロール。
func (q *Queries) ListWorkspaceRolesForUser(ctx context.Context, arg ListWorkspaceRolesForUserParams) ([]ListWorkspaceRolesForUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceRolesForUser, arg.UserID, arg.WorkspaceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceRolesForUserRow{}
	for rows.Next() {
		var i ListWorkspaceRolesForUserRow
		if err := rows.Scan(&i.WorkspaceID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
