// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package store

import (
	"context"
	"time"

	ulid "github.com/oklog/ulid/v2"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :exec
INSERT INTO workspace_members (workspace_id, user_id, role, joined_at)
VALUES ($1, $2, $3, $4::timestamptz)
`

type AddWorkspaceMemberParams struct {
	WorkspaceID ulid.ULID
	UserID      ulid.ULID
	Role        string
	Now         time.Time
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, addWorkspaceMember,
		arg.WorkspaceID,
		arg.UserID,
		arg.Role,
		arg.Now,
	)
	return err
}

const createWorkspace = `-- name: CreateWorkspace :one

INSERT INTO workspaces (id, slug, name, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4,
        $5::timestamptz, $5::timestamptz)
RETURNING id, slug, name, invite_policy, created_by, created_at, updated_at, deleted_at
`

type CreateWorkspaceParams struct {
	ID        ulid.ULID
	Slug      string
	Name      string
	CreatedBy ulid.ULID
	Now       time.Time
}

// ワークスペースとメンバー（ADR 0006 / 0011）。
//
// users は公開プロフィールの列（id / handle / display_name / avatar_object_key / deleted_at）だけを読む（ADR 0011）。
func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.CreatedBy,
		arg.Now,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.InvitePolicy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteRoomMembershipsInWorkspace = `-- name: DeleteRoomMembershipsInWorkspace :exec
DELETE FROM room_members rm
 USING rooms r
 WHERE rm.room_id = r.id
   AND r.workspace_id = $1
   AND rm.user_id = $2
`

type DeleteRoomMembershipsInWorkspaceParams struct {
	WorkspaceID ulid.ULID
	UserID      ulid.ULID
}

// ワークスペースから外れたら、そのワークスペースのルームからも外す（DM を含む）。
// ワークスペースのメンバーでない人の room_members が残ると、再参加したときに private ルームへ戻れてしまう。
func (q *Queries) DeleteRoomMembershipsInWorkspace(ctx context.Context, arg DeleteRoomMembershipsInWorkspaceParams) error {
	_, err := q.db.Exec(ctx, deleteRoomMembershipsInWorkspace, arg.WorkspaceID, arg.UserID)
	return err
}

const deleteWorkspaceMember = `-- name: DeleteWorkspaceMember :exec
DELETE FROM workspace_members
 WHERE workspace_id = $1
   AND user_id = $2
`

type DeleteWorkspaceMemberParams struct {
	WorkspaceID ulid.ULID
	UserID      ulid.ULID
}

func (q *Queries) DeleteWorkspaceMember(ctx context.Context, arg DeleteWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceMember, arg.WorkspaceID, arg.UserID)
	return err
}

const getWorkspaceForUser = `-- name: GetWorkspaceForUser :one
SELECT w.id, w.slug, w.name, w.invite_policy, w.created_by, w.created_at, w.updated_at, w.deleted_at, wm.role,
       (SELECT count(*) FROM workspace_members c WHERE c.workspace_id = w.id) AS member_count
  FROM workspaces w
  JOIN workspace_members wm ON wm.workspace_id = w.id AND wm.user_id = $1
 WHERE w.id = $2
   AND w.deleted_at IS NULL
`

type GetWorkspaceForUserParams struct {
	UserID ulid.ULID
	ID     ulid.ULID
}

type GetWorkspaceForUserRow struct {
	Workspace   Workspace
	Role        string
	MemberCount int64
}

// ワークスペースと、そこでの自分のロール。メンバーでなければ行が返らない（呼び出し側で 404 にする）。
func (q *Queries) GetWorkspaceForUser(ctx context.Context, arg GetWorkspaceForUserParams) (GetWorkspaceForUserRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceForUser, arg.UserID, arg.ID)
	var i GetWorkspaceForUserRow
	err := row.Scan(
		&i.Workspace.ID,
		&i.Workspace.Slug,
		&i.Workspace.Name,
		&i.Workspace.InvitePolicy,
		&i.Workspace.CreatedBy,
		&i.Workspace.CreatedAt,
		&i.Workspace.UpdatedAt,
		&i.Workspace.DeletedAt,
		&i.Role,
		&i.MemberCount,
	)
	return i, err
}

const getWorkspaceMember = `-- name: GetWorkspaceMember :one
SELECT wm.user_id, wm.role, wm.joined_at, u.handle, u.display_name
  FROM workspace_members wm
  JOIN users u ON u.id = wm.user_id
 WHERE wm.workspace_id = $1
   AND wm.user_id = $2
   AND u.deleted_at IS NULL
`

type GetWorkspaceMemberParams struct {
	WorkspaceID ulid.ULID
	UserID      ulid.ULID
}

type GetWorkspaceMemberRow struct {
	UserID      ulid.ULID
	Role        string
	JoinedAt    time.Time
	Handle      string
	DisplayName string
}

func (q *Queries) GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (GetWorkspaceMemberRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var i GetWorkspaceMemberRow
	err := row.Scan(
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.Handle,
		&i.DisplayName,
	)
	return i, err
}

const getWorkspaceMemberRoles = `-- name: GetWorkspaceMemberRoles :many
SELECT wm.user_id, wm.role
  FROM workspace_members wm
  JOIN workspaces w ON w.id = wm.workspace_id
 WHERE wm.workspace_id = $1
   AND wm.user_id = ANY($2::uuid[])
   AND w.deleted_at IS NULL
`

type GetWorkspaceMemberRolesParams struct {
	WorkspaceID ulid.ULID
	UserIds     []ulid.ULID
}

type GetWorkspaceMemberRolesRow struct {
	UserID ulid.ULID
	Role   string
}

// user_ids のワークスペースでのロール。読み取りだけの API で使い、ロックしない。
func (q *Queries) GetWorkspaceMemberRoles(ctx context.Context, arg GetWorkspaceMemberRolesParams) ([]GetWorkspaceMemberRolesRow, error) {
	rows, err := q.db.Query(ctx, getWorkspaceMemberRoles, arg.WorkspaceID, arg.UserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWorkspaceMemberRolesRow{}
	for rows.Next() {
		var i GetWorkspaceMemberRolesRow
		if err := rows.Scan(&i.UserID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceRole = `-- name: GetWorkspaceRole :one
SELECT wm.role
  FROM workspace_members wm
  JOIN workspaces w ON w.id = wm.workspace_id
 WHERE wm.workspace_id = $1
   AND wm.user_id = $2
   AND w.deleted_at IS NULL
`

type GetWorkspaceRoleParams struct {
	WorkspaceID ulid.ULID
	UserID      ulid.ULID
}

// 自分のロールだけを読む（ロックしない）。読み取りの API の「メンバーか」の確認に使う。
func (q *Queries) GetWorkspaceRole(ctx context.Context, arg GetWorkspaceRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getWorkspaceRole, arg.WorkspaceID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getWorkspaceRoleForShare = `-- name: GetWorkspaceRoleForShare :one
SELECT wm.role, w.invite_policy
  FROM workspace_members wm
  JOIN workspaces w ON w.id = wm.workspace_id
 WHERE wm.workspace_id = $1
   AND wm.user_id = $2
   AND w.deleted_at IS NULL
   FOR SHARE OF wm
`

type GetWorkspaceRoleForShareParams struct {
	WorkspaceID ulid.ULID
	UserID      ulid.ULID
}

type GetWorkspaceRoleForShareRow struct {
	Role         string
	InvitePolicy string
}

// 管理操作の前に、自分のロールを読んで共有ロックする。
// ロールの変更・キック（FOR UPDATE）と競合させ、判定してから書き込むまでの間に降格・キックされないようにする。
func (q *Queries) GetWorkspaceRoleForShare(ctx context.Context, arg GetWorkspaceRoleForShareParams) (GetWorkspaceRoleForShareRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceRoleForShare, arg.WorkspaceID, arg.UserID)
	var i GetWorkspaceRoleForShareRow
	err := row.Scan(&i.Role, &i.InvitePolicy)
	return i, err
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT wm.user_id, wm.role, wm.joined_at, u.handle, u.display_name
  FROM workspace_members wm
  JOIN users u ON u.id = wm.user_id
 WHERE wm.workspace_id = $1
   AND wm.user_id > $2
   AND u.deleted_at IS NULL
 ORDER BY wm.user_id
 LIMIT $3
`

type ListWorkspaceMembersParams struct {
	WorkspaceID ulid.ULID
	After       ulid.ULID
	MaxRows     int32
}

type ListWorkspaceMembersRow struct {
	UserID      ulid.ULID
	Role        string
	JoinedAt    time.Time
	Handle      string
	DisplayName string
}

// メンバー一覧。主キー (workspace_id, user_id) の順に走査するので、user_id をカーソルにする。
// 退会済みのユーザーは表示しない（退会時に行を消す実装になるまでの保険）。
func (q *Queries) ListWorkspaceMembers(ctx context.Context, arg ListWorkspaceMembersParams) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, arg.WorkspaceID, arg.After, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceMembersRow{}
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Handle,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
SELECT w.id, w.slug, w.name, w.invite_policy, w.created_by, w.created_at, w.updated_at, w.deleted_at, wm.role
  FROM workspace_members wm
  JOIN workspaces w ON w.id = wm.workspace_id
 WHERE wm.user_id = $1
   AND w.deleted_at IS NULL
 ORDER BY w.id
`

type ListWorkspacesForUserRow struct {
	Workspace Workspace
	Role      string
}

// 自分が所属するワークスペース。user_id のインデックスから引く。
func (q *Queries) ListWorkspacesForUser(ctx context.Context, userID ulid.ULID) ([]ListWorkspacesForUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesForUserRow{}
	for rows.Next() {
		var i ListWorkspacesForUserRow
		if err := rows.Scan(
			&i.Workspace.ID,
			&i.Workspace.Slug,
			&i.Workspace.Name,
			&i.Workspace.InvitePolicy,
			&i.Workspace.CreatedBy,
			&i.Workspace.CreatedAt,
			&i.Workspace.UpdatedAt,
			&i.Workspace.DeletedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkspaceMembers = `-- name: LockWorkspaceMembers :many
SELECT wm.user_id, wm.role
  FROM workspace_members wm
  JOIN workspaces w ON w.id = wm.workspace_id
 WHERE wm.workspace_id = $1
   AND wm.user_id = ANY($2::uuid[])
   AND w.deleted_at IS NULL
 ORDER BY wm.user_id
   FOR UPDATE OF wm
`

type LockWorkspaceMembersParams struct {
	WorkspaceID ulid.ULID
	UserIds     []ulid.ULID
}

type LockWorkspaceMembersRow struct {
	UserID ulid.ULID
	Role   string
}

// ロールの変更・キック・譲渡の対象の行（actor と target）をロックして、ロック後のロールを返す。
// 行ロックは user_id の順に取る。「A が B を降格」と「B が A をキック」が同時に起きても、
// 両方が同じ順でロックを待つのでデッドロックにならない（ADR 0011）。
func (q *Queries) LockWorkspaceMembers(ctx context.Context, arg LockWorkspaceMembersParams) ([]LockWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, lockWorkspaceMembers, arg.WorkspaceID, arg.UserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockWorkspaceMembersRow{}
	for rows.Next() {
		var i LockWorkspaceMembersRow
		if err := rows.Scan(&i.UserID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shareLockWorkspaceMembers = `-- name: ShareLockWorkspaceMembers :many
SELECT wm.user_id, wm.role
  FROM workspace_members wm
  JOIN workspaces w ON w.id = wm.workspace_id
 WHERE wm.workspace_id = $1
   AND wm.user_id = ANY($2::uuid[])
   AND w.deleted_at IS NULL
 ORDER BY wm.user_id
   FOR SHARE OF wm
`

type ShareLockWorkspaceMembersParams struct {
	WorkspaceID ulid.ULID
	UserIds     []ulid.ULID
}

type ShareLockWorkspaceMembersRow struct {
	UserID ulid.ULID
	Role   string
}

// ルームのメンバーを増やす操作（参加・追加・DM）の前に、関係する人の workspace_members の行を共有ロックする。
// キック（FOR UPDATE）と直列化し、「キックがルームの参加を消した後に、並行した参加が room_members を入れる」ことを防ぐ。
// そのまま残ると、同じ人がワークスペースに戻ったときに、招かれていない private ルームに入れてしまう。
// 行のロックは LockWorkspaceMembers と同じく user_id の順に取る。
func (q *Queries) ShareLockWorkspaceMembers(ctx context.Context, arg ShareLockWorkspaceMembersParams) ([]ShareLockWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, shareLockWorkspaceMembers, arg.WorkspaceID, arg.UserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShareLockWorkspaceMembersRow{}
	for rows.Next() {
		var i ShareLockWorkspaceMembersRow
		if err := rows.Scan(&i.UserID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces
   SET name          = coalesce($1, name),
       invite_policy = coalesce($2, invite_policy),
       updated_at    = $3::timestamptz
 WHERE id = $4
RETURNING id, slug, name, invite_policy, created_by, created_at, updated_at, deleted_at
`

type UpdateWorkspaceParams struct {
	Name         *string
	InvitePolicy *string
	Now          time.Time
	ID           ulid.ULID
}

// NULL を渡した項目は変更しない（PATCH）。
func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace,
		arg.Name,
		arg.InvitePolicy,
		arg.Now,
		arg.ID,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.InvitePolicy,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateWorkspaceMemberRole = `-- name: UpdateWorkspaceMemberRole :exec
UPDATE workspace_members
   SET role = $1
 WHERE workspace_id = $2
   AND user_id = $3
`

type UpdateWorkspaceMemberRoleParams struct {
	Role        string
	WorkspaceID ulid.ULID
	UserID      ulid.ULID
}

func (q *Queries) UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateWorkspaceMemberRole, arg.Role, arg.WorkspaceID, arg.UserID)
	return err
}
