// Code generated by internal/httpx/tsgen_test.go. DO NOT EDIT.
// Go の型を変えたら `make ts-types` で生成し直す（ロードマップ Phase 6-2）。

/** Problem の type に付く接頭辞。ProblemType はこれを除いた部分。 */
export const PROBLEM_TYPE_PREFIX = "tag:hibari,2026:problem:";

export type Role = "owner" | "admin" | "member";

export type InvitePolicy = "admins_only" | "all_members";

export type RoomKind = "public" | "private" | "dm";

export type InviteStatus = "active" | "exhausted" | "expired" | "revoked";

export type AttachmentStatus = "pending" | "uploaded" | "attached" | "deleted";

export type RemovalReason = "left" | "removed";

export type ProblemType = "bad-request" | "validation-error" | "unauthenticated" | "forbidden" | "not-found" | "internal" | "rate-limited" | "invalid-credentials" | "invalid-refresh-token" | "invalid-one-time-token" | "handle-taken" | "email-taken" | "avatar-not-uploaded" | "avatar-mismatch" | "invite-invalid" | "invite-expired" | "invite-exhausted" | "owner-must-transfer" | "room-name-taken" | "user-not-in-workspace" | "message-deleted" | "attachment-not-uploaded" | "attachment-mismatch" | "ws-ticket-invalid";

export type ClientMessageType = "subscribe" | "unsubscribe" | "typing" | "ping";

export type AckError = "invalid_message" | "not_found" | "not_subscribed" | "forbidden" | "too_many_subscriptions" | "internal";

export interface Problem {
  type: string;
  title: string;
  status: number;
  detail?: string;
  /** request_id は問い合わせのときにログと突き合わせるための拡張メンバー。 */
  request_id?: string;
  /** errors は入力の検証エラーの拡張メンバー。 */
  errors?: ProblemFieldError[];
}

export interface ProblemFieldError {
  field: string;
  reason: string;
}

export interface Health {
  status: string;
  checks: Record<string, string>;
}

export interface RegisterRequest {
  handle: string;
  display_name: string;
  email: string;
  password: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface RefreshTokenRequest {
  refresh_token: string;
}

export interface OneTimeTokenRequest {
  token: string;
}

export interface PasswordResetRequest {
  email: string;
}

export interface PasswordResetConfirmRequest {
  token: string;
  password: string;
}

export interface TokenResponse {
  user?: User;
  access_token: string;
  token_type: string;
  expires_in: number;
  /** Refresh Token はボディ方式のときだけ入る。Cookie 方式ではレスポンスのボディに出さない。 */
  refresh_token?: string;
  refresh_token_expires_at?: string;
}

export interface User {
  id: string;
  handle: string;
  display_name: string;
  email: string;
  email_verified: boolean;
  /** avatar_url は署名付きの GET URL。画像がなければ入らない（ADR 0020）。 */
  avatar_url?: string;
  created_at: string;
}

export interface UpdateProfileRequest {
  display_name?: string | null;
  handle?: string | null;
}

export interface Session {
  id: string;
  user_agent: string;
  current: boolean;
  started_at: string;
  last_used_at: string;
}

export interface SessionList {
  sessions: Session[];
}

export interface RevokeSessionsResponse {
  revoked_count: number;
}

export interface AvatarUploadRequest {
  content_type: string;
  size_bytes?: number | null;
}

export interface AvatarUpload {
  upload_id: string;
  upload: Upload;
}

export interface CompleteAvatarUploadRequest {
  upload_id: string;
  content_type: string;
  size_bytes?: number | null;
}

export interface AvatarURLsRequest {
  user_ids: string[];
}

export interface AvatarURLs {
  avatars: Record<string, SignedURL>;
}

export interface Upload {
  method: string;
  url: string;
  /** headers はクライアントが PUT に付けなければならないヘッダー。値が違うと署名が合わずにストレージが拒否する。 */
  headers: Record<string, string>;
  expires_at: string;
}

export interface SignedURL {
  url: string;
  expires_at: string;
}

export interface UserProfile {
  id: string;
  handle: string;
  display_name: string;
}

export interface CreateWorkspaceRequest {
  name: string;
}

export interface UpdateWorkspaceRequest {
  name?: string | null;
  invite_policy?: InvitePolicy | null;
}

export interface Workspace {
  id: string;
  slug: string;
  name: string;
  invite_policy: InvitePolicy;
  my_role: Role;
  /** member_count は 1 件の取得でだけ返す。 */
  member_count?: number;
  created_at: string;
  updated_at: string;
}

export interface WorkspaceList {
  workspaces: Workspace[];
}

export interface Member {
  user: UserProfile;
  role: Role;
  joined_at: string;
}

export interface MemberList {
  members: Member[];
  next_cursor: string | null;
}

export interface ChangeMemberRoleRequest {
  role: Role;
}

export interface TransferOwnershipRequest {
  user_id: string;
}

export interface CreateInviteRequest {
  /** max_uses が null（または省略）なら無制限。 */
  max_uses?: number | null;
  expires_in_seconds?: number | null;
}

export interface Invite {
  id: string;
  workspace_id: string;
  created_by: UserProfile;
  max_uses: number | null;
  use_count: number;
  expires_at: string;
  revoked_at: string | null;
  created_at: string;
  status: InviteStatus;
  /** code は作成のレスポンスでだけ返す。一覧では再表示しない（ADR 0006）。 */
  code?: string;
}

export interface InviteList {
  invites: Invite[];
  next_cursor: string | null;
}

export interface InvitePreview {
  workspace: InvitePreviewWorkspace;
  inviter: UserProfile;
  already_member: boolean;
  expires_at: string;
}

export interface InvitePreviewWorkspace {
  id: string;
  name: string;
  member_count: number;
  public_room_count: number;
}

export interface InviteAcceptance {
  workspace: Workspace;
  already_member: boolean;
}

export interface CreateRoomRequest {
  kind: RoomKind;
  name?: string;
  user_id?: string;
}

export interface UpdateRoomRequest {
  name?: string | null;
  is_default?: boolean | null;
}

export interface Room {
  id: string;
  workspace_id: string;
  kind: RoomKind;
  /** name は dm では null。 */
  name: string | null;
  is_default: boolean;
  is_member: boolean;
  /** member_count は 1 件の取得でだけ返す。 */
  member_count?: number;
  dm_peer?: DMPeer;
  last_message_seq: number;
  last_message_at: string | null;
  /** last_read_seq はルームのメンバーでなければ null。 */
  last_read_seq: number | null;
  unread_count: number;
  /** last_message はメッセージが 1 件もなければ null。 */
  last_message: LastMessage | null;
  created_at: string;
}

export interface RoomList {
  rooms: Room[];
}

export interface DMPeer {
  id: string;
  handle: string;
  display_name: string;
  online: boolean;
}

export interface LastMessage {
  id: string;
  sender: UserProfile;
  body: string;
  created_at: string;
  deleted: boolean;
}

export interface AddRoomMemberRequest {
  user_id: string;
}

export interface RoomMember {
  user: UserProfile;
  role: Role;
  joined_at: string;
  online: boolean;
}

export interface RoomMemberList {
  members: RoomMember[];
  next_cursor: string | null;
}

export interface SendMessageRequest {
  client_msg_id: string;
  body: string;
  reply_to_id?: string;
  attachment_ids?: string[];
}

export interface EditMessageRequest {
  body: string;
}

export interface Message {
  id: string;
  room_id: string;
  seq: number;
  /** change_seq は同期のカーソル（ADR 0014）。表示の並びには seq を使う。 */
  change_seq: number;
  sender: UserProfile;
  /** client_msg_id は、クライアントが楽観的に表示したメッセージと、REST / WebSocket で届いたメッセージを突き合わせるために返す（ADR 0004）。 */
  client_msg_id: string;
  body: string;
  reply_to: ReplyPreview | null;
  /** attachments は削除済みのメッセージでは空配列。GET URL は含めない（ADR 0013）。 */
  attachments: MessageAttachment[];
  created_at: string;
  edited_at: string | null;
  deleted_at: string | null;
}

export interface ReplyPreview {
  id: string;
  seq: number;
  sender: UserProfile;
  body: string;
  deleted: boolean;
}

export interface MessageAttachment {
  id: string;
  file_name: string;
  content_type: string;
  size_bytes: number;
  width: number | null;
  height: number | null;
}

export interface MessageList {
  messages: Message[];
  has_more: boolean;
  /** last_change_seq はメッセージを読む前のルームの last_change_seq。クライアントは change_seq のカーソルをこの値まで進めてよい。 */
  last_change_seq: number;
}

export interface MarkRoomReadRequest {
  seq?: number | null;
}

export interface ReadState {
  last_read_seq: number;
  unread_count: number;
}

export interface CreateAttachmentRequest {
  file_name: string;
  content_type: string;
  size_bytes?: number | null;
  width?: number | null;
  height?: number | null;
}

export interface CreateAttachmentResponse {
  attachment: Attachment;
  upload: Upload;
}

export interface Attachment {
  id: string;
  room_id: string;
  status: AttachmentStatus;
  file_name: string;
  content_type: string;
  size_bytes: number;
  width: number | null;
  height: number | null;
  created_at: string;
}

export interface WSTicket {
  ticket: string;
  expires_in: number;
}

export interface ClientMessage {
  type: ClientMessageType;
  id?: string | null;
  /** room_id と WorkspaceID は、subscribe / unsubscribe ではどちらか 1 つ、typing では room_id だけを使う。 */
  room_id?: string;
  workspace_id?: string;
}

export interface Ack {
  type: "ack";
  id?: string;
  error?: AckError;
}

export interface MemberJoinedData {
  workspace_id: string;
  room_id: string;
  user: UserProfile;
}

export interface MemberLeftData {
  workspace_id: string;
  room_id: string;
  user_id: string;
}

export interface RoomUpdatedData {
  workspace_id: string;
  room_id: string;
  name: string;
  is_default: boolean;
}

export interface RoomMemberRemovedData {
  workspace_id: string;
  room_id: string;
  reason: RemovalReason;
}

export interface RoomReadData {
  workspace_id: string;
  room_id: string;
  last_read_seq: number;
  unread_count: number;
}

export interface WorkspaceUpdatedData {
  workspace_id: string;
  name: string;
  invite_policy: InvitePolicy;
}

export interface WorkspaceMemberRemovedData {
  workspace_id: string;
  user_id: string;
  reason: RemovalReason;
}

export interface WorkspaceRoleChangedData {
  workspace_id: string;
  user_id: string;
  role: Role;
}

export interface PresenceChangedData {
  user_id: string;
  online: boolean;
}

export interface TypingStartedData {
  workspace_id: string;
  room_id: string;
  user: UserProfile;
}

/** サーバーからのイベント（docs/events.md）。type で data の型が決まる。 */
export type ServerEvent =
  | { type: "message.created"; data: Message }
  | { type: "message.updated"; data: Message }
  | { type: "message.deleted"; data: Message }
  | { type: "member.joined"; data: MemberJoinedData }
  | { type: "member.left"; data: MemberLeftData }
  | { type: "room.updated"; data: RoomUpdatedData }
  | { type: "room.member_removed"; data: RoomMemberRemovedData }
  | { type: "room.read"; data: RoomReadData }
  | { type: "workspace.updated"; data: WorkspaceUpdatedData }
  | { type: "workspace.member_removed"; data: WorkspaceMemberRemovedData }
  | { type: "workspace.role_changed"; data: WorkspaceRoleChangedData }
  | { type: "presence.changed"; data: PresenceChangedData }
  | { type: "typing.started"; data: TypingStartedData };

export type ServerEventType = ServerEvent["type"];

/** サーバーから届く WebSocket のフレーム。イベントか ack のどちらか。 */
export type ServerMessage = ServerEvent | Ack;
