// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	ulid "github.com/oklog/ulid/v2"
)

type User struct {
	ID              ulid.ULID
	Handle          string
	DisplayName     string
	Email           string
	EmailVerifiedAt *time.Time
	PasswordHash    *string
	AvatarObjectKey *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       *time.Time
}
