// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: one_time_tokens.sql

package store

import (
	"context"
	"time"

	ulid "github.com/oklog/ulid/v2"
)

const consumeOneTimeToken = `-- name: ConsumeOneTimeToken :one
UPDATE one_time_tokens
   SET consumed_at = $1::timestamptz
 WHERE token_hash = $2
   AND purpose = $3
   AND consumed_at IS NULL
   AND expires_at > $1::timestamptz
RETURNING user_id
`

type ConsumeOneTimeTokenParams struct {
	Now       time.Time
	TokenHash []byte
	Purpose   string
}

// 未使用・期限内のトークンを使用済みにして、持ち主を返す。
// 「読んで確かめてから更新」を 1 文にするので、同じリンクを同時に開いても成功するのは 1 回だけ。
func (q *Queries) ConsumeOneTimeToken(ctx context.Context, arg ConsumeOneTimeTokenParams) (ulid.ULID, error) {
	row := q.db.QueryRow(ctx, consumeOneTimeToken, arg.Now, arg.TokenHash, arg.Purpose)
	var user_id ulid.ULID
	err := row.Scan(&user_id)
	return user_id, err
}

const createOneTimeToken = `-- name: CreateOneTimeToken :exec
INSERT INTO one_time_tokens (id, user_id, purpose, token_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5,
        $6::timestamptz)
`

type CreateOneTimeTokenParams struct {
	ID        ulid.ULID
	UserID    ulid.ULID
	Purpose   string
	TokenHash []byte
	ExpiresAt time.Time
	Now       time.Time
}

func (q *Queries) CreateOneTimeToken(ctx context.Context, arg CreateOneTimeTokenParams) error {
	_, err := q.db.Exec(ctx, createOneTimeToken,
		arg.ID,
		arg.UserID,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Now,
	)
	return err
}

const deleteUnconsumedOneTimeTokens = `-- name: DeleteUnconsumedOneTimeTokens :exec
DELETE FROM one_time_tokens
 WHERE user_id = $1
   AND purpose = $2
   AND consumed_at IS NULL
`

type DeleteUnconsumedOneTimeTokensParams struct {
	UserID  ulid.ULID
	Purpose string
}

// 新しいトークンを発行する前に、同じ用途の未使用のトークンを消す。
// 確認メールやリセットのメールを何通も要求されても、有効なリンクは常に最新の 1 つだけにする。
func (q *Queries) DeleteUnconsumedOneTimeTokens(ctx context.Context, arg DeleteUnconsumedOneTimeTokensParams) error {
	_, err := q.db.Exec(ctx, deleteUnconsumedOneTimeTokens, arg.UserID, arg.Purpose)
	return err
}
