// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package store

import (
	"context"
	"net/netip"
	"time"

	ulid "github.com/oklog/ulid/v2"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, user_id, family_id, token_hash, rotated_from, expires_at, user_agent, ip, created_at)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9::timestamptz)
`

type CreateRefreshTokenParams struct {
	ID          ulid.ULID
	UserID      ulid.ULID
	FamilyID    ulid.ULID
	TokenHash   []byte
	RotatedFrom *ulid.ULID
	ExpiresAt   time.Time
	UserAgent   *string
	Ip          *netip.Addr
	Now         time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.RotatedFrom,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
		arg.Now,
	)
	return err
}

const getRefreshTokenFamily = `-- name: GetRefreshTokenFamily :one
SELECT family_id
  FROM refresh_tokens
 WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenFamily(ctx context.Context, tokenHash []byte) (ulid.ULID, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenFamily, tokenHash)
	var family_id ulid.ULID
	err := row.Scan(&family_id)
	return family_id, err
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT rt.id, rt.user_id, rt.family_id, rt.expires_at, rt.revoked_at, rt.revoked_reason
  FROM refresh_tokens rt
  JOIN users u ON u.id = rt.user_id
 WHERE rt.token_hash = $1
   AND u.deleted_at IS NULL
   FOR UPDATE OF rt
`

type GetRefreshTokenForUpdateRow struct {
	ID            ulid.ULID
	UserID        ulid.ULID
	FamilyID      ulid.ULID
	ExpiresAt     time.Time
	RevokedAt     *time.Time
	RevokedReason *string
}

// ローテーションの対象を行ロックして読む。
// 同じトークンで同時に refresh されても、2 本目は 1 本目のコミットを待ってから
// 「rotated で失効済み」の状態を読むので、必ず再利用として検知される。
// 退会済みのユーザーのトークンは見つからないものとして扱う。
func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, tokenHash []byte) (GetRefreshTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, tokenHash)
	var i GetRefreshTokenForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const markRefreshTokenRotated = `-- name: MarkRefreshTokenRotated :exec
UPDATE refresh_tokens
   SET revoked_at     = $1::timestamptz,
       revoked_reason = 'rotated'
 WHERE id = $2
`

type MarkRefreshTokenRotatedParams struct {
	Now time.Time
	ID  ulid.ULID
}

func (q *Queries) MarkRefreshTokenRotated(ctx context.Context, arg MarkRefreshTokenRotatedParams) error {
	_, err := q.db.Exec(ctx, markRefreshTokenRotated, arg.Now, arg.ID)
	return err
}

const revokeAllRefreshTokensForUser = `-- name: RevokeAllRefreshTokensForUser :execrows
UPDATE refresh_tokens
   SET revoked_at     = $1::timestamptz,
       revoked_reason = $2::text
 WHERE user_id = $3
   AND revoked_at IS NULL
`

type RevokeAllRefreshTokensForUserParams struct {
	Now    time.Time
	Reason string
	UserID ulid.ULID
}

// ユーザーの全セッションの失効（パスワードリセット）。
func (q *Queries) RevokeAllRefreshTokensForUser(ctx context.Context, arg RevokeAllRefreshTokensForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllRefreshTokensForUser, arg.Now, arg.Reason, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :execrows
UPDATE refresh_tokens
   SET revoked_at     = $1::timestamptz,
       revoked_reason = $2::text
 WHERE family_id = $3
   AND revoked_at IS NULL
`

type RevokeRefreshTokenFamilyParams struct {
	Now      time.Time
	Reason   string
	FamilyID ulid.ULID
}

// セッション（family）単位の失効。rotated_from を再帰で辿らず、family_id の 1 文で全部を失効させる（ADR 0007）。
// すでに失効している行（rotated を含む）は理由を上書きしない。影響行数が 0 なら、すでに失効済みだったことを表す。
func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, arg RevokeRefreshTokenFamilyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokenFamily, arg.Now, arg.Reason, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
