// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package store

import (
	"context"
	"net/netip"
	"time"

	ulid "github.com/oklog/ulid/v2"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, user_id, family_id, token_hash, rotated_from, expires_at, user_agent, ip, created_at)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9::timestamptz)
`

type CreateRefreshTokenParams struct {
	ID          ulid.ULID
	UserID      ulid.ULID
	FamilyID    ulid.ULID
	TokenHash   []byte
	RotatedFrom *ulid.ULID
	ExpiresAt   time.Time
	UserAgent   *string
	Ip          *netip.Addr
	Now         time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.RotatedFrom,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
		arg.Now,
	)
	return err
}

const getRefreshTokenFamily = `-- name: GetRefreshTokenFamily :one
SELECT family_id
  FROM refresh_tokens
 WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenFamily(ctx context.Context, tokenHash []byte) (ulid.ULID, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenFamily, tokenHash)
	var family_id ulid.ULID
	err := row.Scan(&family_id)
	return family_id, err
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT rt.id, rt.user_id, rt.family_id, rt.expires_at, rt.revoked_at, rt.revoked_reason
  FROM refresh_tokens rt
  JOIN users u ON u.id = rt.user_id
 WHERE rt.token_hash = $1
   AND u.deleted_at IS NULL
   FOR UPDATE OF rt
`

type GetRefreshTokenForUpdateRow struct {
	ID            ulid.ULID
	UserID        ulid.ULID
	FamilyID      ulid.ULID
	ExpiresAt     time.Time
	RevokedAt     *time.Time
	RevokedReason *string
}

// ローテーションの対象を行ロックして読む。
// 同じトークンで同時に refresh されても、2 本目は 1 本目のコミットを待ってから
// 「rotated で失効済み」の状態を読むので、必ず再利用として検知される。
// 退会済みのユーザーのトークンは見つからないものとして扱う。
func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, tokenHash []byte) (GetRefreshTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, tokenHash)
	var i GetRefreshTokenForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const isSessionActive = `-- name: IsSessionActive :one
SELECT EXISTS (
    SELECT 1
      FROM refresh_tokens rt
      JOIN users u ON u.id = rt.user_id
     WHERE rt.family_id = $1
       AND rt.user_id = $2
       AND rt.revoked_at IS NULL
       AND rt.expires_at > $3::timestamptz
       AND u.deleted_at IS NULL
)::boolean
`

type IsSessionActiveParams struct {
	FamilyID ulid.ULID
	UserID   ulid.ULID
	Now      time.Time
}

// セッション（family）に、未失効で期限内の Refresh Token が残っているか（ADR 0015）。
// ローテーション済みの行は revoked_at を持つが、family の最新の行が未失効なら、セッションは生きている。
// 退会済みのユーザーのセッションは生きていないものとして扱う。インデックス refresh_tokens(family_id) を使う。
func (q *Queries) IsSessionActive(ctx context.Context, arg IsSessionActiveParams) (bool, error) {
	row := q.db.QueryRow(ctx, isSessionActive, arg.FamilyID, arg.UserID, arg.Now)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT family_id, user_agent, last_used_at, started_at
  FROM (
    SELECT DISTINCT ON (rt.family_id)
           rt.family_id,
           rt.user_agent,
           rt.created_at AS last_used_at,
           (SELECT min(f.created_at) FROM refresh_tokens f WHERE f.family_id = rt.family_id)::timestamptz AS started_at
      FROM refresh_tokens rt
     WHERE rt.user_id = $1
       AND rt.revoked_at IS NULL
       AND rt.expires_at > $2::timestamptz
     ORDER BY rt.family_id, rt.created_at DESC
  ) s
 ORDER BY s.last_used_at DESC
`

type ListActiveSessionsParams struct {
	UserID ulid.ULID
	Now    time.Time
}

type ListActiveSessionsRow struct {
	FamilyID   ulid.ULID
	UserAgent  *string
	LastUsedAt time.Time
	StartedAt  time.Time
}

// 設定画面の「ログイン中のデバイス」（ADR 0019）。
// セッション（family）ごとに 1 行にまとめる。family の中で未失効なのは最新の 1 行だけなので、
// その行の user_agent を「その端末」の情報として使い、family の最初の行の時刻をログインの時刻とする。
func (q *Queries) ListActiveSessions(ctx context.Context, arg ListActiveSessionsParams) ([]ListActiveSessionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveSessions, arg.UserID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveSessionsRow{}
	for rows.Next() {
		var i ListActiveSessionsRow
		if err := rows.Scan(
			&i.FamilyID,
			&i.UserAgent,
			&i.LastUsedAt,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRefreshTokenRotated = `-- name: MarkRefreshTokenRotated :exec
UPDATE refresh_tokens
   SET revoked_at     = $1::timestamptz,
       revoked_reason = 'rotated'
 WHERE id = $2
`

type MarkRefreshTokenRotatedParams struct {
	Now time.Time
	ID  ulid.ULID
}

func (q *Queries) MarkRefreshTokenRotated(ctx context.Context, arg MarkRefreshTokenRotatedParams) error {
	_, err := q.db.Exec(ctx, markRefreshTokenRotated, arg.Now, arg.ID)
	return err
}

const revokeAllRefreshTokensForUser = `-- name: RevokeAllRefreshTokensForUser :execrows
UPDATE refresh_tokens
   SET revoked_at     = $1::timestamptz,
       revoked_reason = $2::text
 WHERE user_id = $3
   AND revoked_at IS NULL
`

type RevokeAllRefreshTokensForUserParams struct {
	Now    time.Time
	Reason string
	UserID ulid.ULID
}

// ユーザーの全セッションの失効（パスワードリセット）。
func (q *Queries) RevokeAllRefreshTokensForUser(ctx context.Context, arg RevokeAllRefreshTokensForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllRefreshTokensForUser, arg.Now, arg.Reason, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeOtherSessions = `-- name: RevokeOtherSessions :many
UPDATE refresh_tokens
   SET revoked_at     = $1::timestamptz,
       revoked_reason = $2::text
 WHERE user_id = $3
   AND family_id <> $4
   AND revoked_at IS NULL
RETURNING family_id
`

type RevokeOtherSessionsParams struct {
	Now          time.Time
	Reason       string
	UserID       ulid.ULID
	KeepFamilyID ulid.ULID
}

// いま使っているセッション以外をすべて失効させ、失効した family を返す（呼び出し側が失効イベントを publish する）。
// 1 つの family に複数の行があれば同じ family_id が複数返るので、呼び出し側で重複を除く。
func (q *Queries) RevokeOtherSessions(ctx context.Context, arg RevokeOtherSessionsParams) ([]ulid.ULID, error) {
	rows, err := q.db.Query(ctx, revokeOtherSessions,
		arg.Now,
		arg.Reason,
		arg.UserID,
		arg.KeepFamilyID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ulid.ULID{}
	for rows.Next() {
		var family_id ulid.ULID
		if err := rows.Scan(&family_id); err != nil {
			return nil, err
		}
		items = append(items, family_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :execrows
UPDATE refresh_tokens
   SET revoked_at     = $1::timestamptz,
       revoked_reason = $2::text
 WHERE family_id = $3
   AND revoked_at IS NULL
`

type RevokeRefreshTokenFamilyParams struct {
	Now      time.Time
	Reason   string
	FamilyID ulid.ULID
}

// セッション（family）単位の失効。rotated_from を再帰で辿らず、family_id の 1 文で全部を失効させる（ADR 0007）。
// すでに失効している行（rotated を含む）は理由を上書きしない。影響行数が 0 なら、すでに失効済みだったことを表す。
func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, arg RevokeRefreshTokenFamilyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokenFamily, arg.Now, arg.Reason, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionForUser = `-- name: RevokeSessionForUser :execrows
UPDATE refresh_tokens
   SET revoked_at     = $1::timestamptz,
       revoked_reason = $2::text
 WHERE user_id = $3
   AND family_id = $4
   AND revoked_at IS NULL
`

type RevokeSessionForUserParams struct {
	Now      time.Time
	Reason   string
	UserID   ulid.ULID
	FamilyID ulid.ULID
}

// 自分のセッションだけを失効させる。user_id の条件で、他人のセッション ID を指定しても 0 行になる。
func (q *Queries) RevokeSessionForUser(ctx context.Context, arg RevokeSessionForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionForUser,
		arg.Now,
		arg.Reason,
		arg.UserID,
		arg.FamilyID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
