// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
	"time"

	ulid "github.com/oklog/ulid/v2"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, handle, display_name, email, password_hash, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5,
        $6::timestamptz, $6::timestamptz)
RETURNING id, handle, display_name, email, email_verified_at, password_hash, avatar_object_key, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	ID           ulid.ULID
	Handle       string
	DisplayName  string
	Email        string
	PasswordHash *string
	Now          time.Time
}

// email と handle の重複は UNIQUE 制約（users_email_key / users_handle_key）で検出する。
// 先に SELECT で確かめると、並行した登録の間に割り込まれるので、制約違反をエラーとして受け取る。
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Handle,
		arg.DisplayName,
		arg.Email,
		arg.PasswordHash,
		arg.Now,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.AvatarObjectKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveUserByEmail = `-- name: GetActiveUserByEmail :one
SELECT id, handle, display_name, email, email_verified_at, password_hash, avatar_object_key, created_at, updated_at, deleted_at
  FROM users
 WHERE email = $1
   AND deleted_at IS NULL
`

// 退会済みのユーザーは存在しないものとして扱う（ログインできない）。
func (q *Queries) GetActiveUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getActiveUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.AvatarObjectKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveUserByID = `-- name: GetActiveUserByID :one
SELECT id, handle, display_name, email, email_verified_at, password_hash, avatar_object_key, created_at, updated_at, deleted_at
  FROM users
 WHERE id = $1
   AND deleted_at IS NULL
`

func (q *Queries) GetActiveUserByID(ctx context.Context, id ulid.ULID) (User, error) {
	row := q.db.QueryRow(ctx, getActiveUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.AvatarObjectKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUserAvatars = `-- name: ListUserAvatars :many
SELECT id, avatar_object_key
  FROM users
 WHERE id = ANY($1::uuid[])
   AND avatar_object_key IS NOT NULL
   AND deleted_at IS NULL
`

type ListUserAvatarsRow struct {
	ID              ulid.ULID
	AvatarObjectKey *string
}

// 画面に出すユーザーのアバターのキーをまとめて読む（ADR 0020）。退会済みは返さない。
func (q *Queries) ListUserAvatars(ctx context.Context, ids []ulid.ULID) ([]ListUserAvatarsRow, error) {
	rows, err := q.db.Query(ctx, listUserAvatars, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAvatarsRow{}
	for rows.Next() {
		var i ListUserAvatarsRow
		if err := rows.Scan(&i.ID, &i.AvatarObjectKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerified = `-- name: MarkEmailVerified :execrows
UPDATE users
   SET email_verified_at = coalesce(email_verified_at, $1::timestamptz),
       updated_at        = $1::timestamptz
 WHERE id = $2
   AND deleted_at IS NULL
`

type MarkEmailVerifiedParams struct {
	Now time.Time
	ID  ulid.ULID
}

// すでに確認済みなら日時を上書きしない（最初に確認した日時を残す）。
func (q *Queries) MarkEmailVerified(ctx context.Context, arg MarkEmailVerifiedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markEmailVerified, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserAvatar = `-- name: SetUserAvatar :one
UPDATE users u
   SET avatar_object_key = $1,
       updated_at        = $2::timestamptz
  FROM users before
 WHERE u.id = $3
   AND before.id = u.id
   AND u.deleted_at IS NULL
RETURNING u.id, u.handle, u.display_name, u.email, u.email_verified_at, u.password_hash, u.avatar_object_key, u.created_at, u.updated_at, u.deleted_at, before.avatar_object_key AS previous_avatar_object_key
`

type SetUserAvatarParams struct {
	AvatarObjectKey *string
	Now             time.Time
	ID              ulid.ULID
}

type SetUserAvatarRow struct {
	User                    User
	PreviousAvatarObjectKey *string
}

// アバター画像の差し替え・削除（ADR 0020）。置き換える前のキーも返し、呼び出し側が古いオブジェクトを消す。
// 自己結合の before は更新前のスナップショットを見るので、置き換える前のキーを同じ 1 文で取れる。
func (q *Queries) SetUserAvatar(ctx context.Context, arg SetUserAvatarParams) (SetUserAvatarRow, error) {
	row := q.db.QueryRow(ctx, setUserAvatar, arg.AvatarObjectKey, arg.Now, arg.ID)
	var i SetUserAvatarRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Handle,
		&i.User.DisplayName,
		&i.User.Email,
		&i.User.EmailVerifiedAt,
		&i.User.PasswordHash,
		&i.User.AvatarObjectKey,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.DeletedAt,
		&i.PreviousAvatarObjectKey,
	)
	return i, err
}

const updatePasswordFromReset = `-- name: UpdatePasswordFromReset :execrows
UPDATE users
   SET password_hash     = $1,
       email_verified_at = coalesce(email_verified_at, $2::timestamptz),
       updated_at        = $2::timestamptz
 WHERE id = $3
   AND deleted_at IS NULL
`

type UpdatePasswordFromResetParams struct {
	PasswordHash *string
	Now          time.Time
	ID           ulid.ULID
}

// リセットのリンクはその email に届いたものなので、email の所有も確認できたとみなす。
func (q *Queries) UpdatePasswordFromReset(ctx context.Context, arg UpdatePasswordFromResetParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePasswordFromReset, arg.PasswordHash, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
   SET display_name = coalesce($1, display_name),
       handle       = coalesce($2::citext, handle),
       updated_at   = $3::timestamptz
 WHERE id = $4
   AND deleted_at IS NULL
RETURNING id, handle, display_name, email, email_verified_at, password_hash, avatar_object_key, created_at, updated_at, deleted_at
`

type UpdateUserProfileParams struct {
	DisplayName *string
	Handle      *string
	Now         time.Time
	ID          ulid.ULID
}

// 表示名とハンドルの変更（ADR 0019）。省略した項目（NULL）は変えない。
// handle の重複は登録と同じく UNIQUE 制約（users_handle_key）の違反として受け取る。
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.DisplayName,
		arg.Handle,
		arg.Now,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.AvatarObjectKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
