// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
	"time"

	ulid "github.com/oklog/ulid/v2"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, handle, display_name, email, password_hash, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5,
        $6::timestamptz, $6::timestamptz)
RETURNING id, handle, display_name, email, email_verified_at, password_hash, avatar_object_key, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	ID           ulid.ULID
	Handle       string
	DisplayName  string
	Email        string
	PasswordHash *string
	Now          time.Time
}

// email と handle の重複は UNIQUE 制約（users_email_key / users_handle_key）で検出する。
// 先に SELECT で確かめると、並行した登録の間に割り込まれるので、制約違反をエラーとして受け取る。
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Handle,
		arg.DisplayName,
		arg.Email,
		arg.PasswordHash,
		arg.Now,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.AvatarObjectKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveUserByEmail = `-- name: GetActiveUserByEmail :one
SELECT id, handle, display_name, email, email_verified_at, password_hash, avatar_object_key, created_at, updated_at, deleted_at
  FROM users
 WHERE email = $1
   AND deleted_at IS NULL
`

// 退会済みのユーザーは存在しないものとして扱う（ログインできない）。
func (q *Queries) GetActiveUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getActiveUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.AvatarObjectKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveUserByID = `-- name: GetActiveUserByID :one
SELECT id, handle, display_name, email, email_verified_at, password_hash, avatar_object_key, created_at, updated_at, deleted_at
  FROM users
 WHERE id = $1
   AND deleted_at IS NULL
`

func (q *Queries) GetActiveUserByID(ctx context.Context, id ulid.ULID) (User, error) {
	row := q.db.QueryRow(ctx, getActiveUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.AvatarObjectKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markEmailVerified = `-- name: MarkEmailVerified :execrows
UPDATE users
   SET email_verified_at = coalesce(email_verified_at, $1::timestamptz),
       updated_at        = $1::timestamptz
 WHERE id = $2
   AND deleted_at IS NULL
`

type MarkEmailVerifiedParams struct {
	Now time.Time
	ID  ulid.ULID
}

// すでに確認済みなら日時を上書きしない（最初に確認した日時を残す）。
func (q *Queries) MarkEmailVerified(ctx context.Context, arg MarkEmailVerifiedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markEmailVerified, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePasswordFromReset = `-- name: UpdatePasswordFromReset :execrows
UPDATE users
   SET password_hash     = $1,
       email_verified_at = coalesce(email_verified_at, $2::timestamptz),
       updated_at        = $2::timestamptz
 WHERE id = $3
   AND deleted_at IS NULL
`

type UpdatePasswordFromResetParams struct {
	PasswordHash *string
	Now          time.Time
	ID           ulid.ULID
}

// リセットのリンクはその email に届いたものなので、email の所有も確認できたとみなす。
func (q *Queries) UpdatePasswordFromReset(ctx context.Context, arg UpdatePasswordFromResetParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePasswordFromReset, arg.PasswordHash, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
