// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
	"time"

	ulid "github.com/oklog/ulid/v2"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, handle, display_name, email, password_hash, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5,
        $6::timestamptz, $6::timestamptz)
RETURNING id, handle, display_name, email, email_verified_at, password_hash, avatar_object_key, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	ID           ulid.ULID
	Handle       string
	DisplayName  string
	Email        string
	PasswordHash *string
	Now          time.Time
}

// email と handle の重複は UNIQUE 制約（users_email_key / users_handle_key）で検出する。
// 先に SELECT で確かめると、並行した登録の間に割り込まれるので、制約違反をエラーとして受け取る。
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Handle,
		arg.DisplayName,
		arg.Email,
		arg.PasswordHash,
		arg.Now,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.AvatarObjectKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveUserByEmail = `-- name: GetActiveUserByEmail :one
SELECT id, handle, display_name, email, email_verified_at, password_hash, avatar_object_key, created_at, updated_at, deleted_at
  FROM users
 WHERE email = $1
   AND deleted_at IS NULL
`

// 退会済みのユーザーは存在しないものとして扱う（ログインできない）。
func (q *Queries) GetActiveUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getActiveUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.AvatarObjectKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveUserByID = `-- name: GetActiveUserByID :one
SELECT id, handle, display_name, email, email_verified_at, password_hash, avatar_object_key, created_at, updated_at, deleted_at
  FROM users
 WHERE id = $1
   AND deleted_at IS NULL
`

func (q *Queries) GetActiveUserByID(ctx context.Context, id ulid.ULID) (User, error) {
	row := q.db.QueryRow(ctx, getActiveUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.AvatarObjectKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
